//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Views.CreditNotes.App_localResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreditNotes_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreditNotes_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Views.CreditNotes.App_localResources.CreditNotes.cshtml", typeof(CreditNotes_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process and Cancel.
        /// </summary>
        public static string btnProcessCancel {
            get {
                return ResourceManager.GetString("btnProcessCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a taxpayer ID.
        /// </summary>
        public static string IssuerIssTaxpayerIdRequired {
            get {
                return ResourceManager.GetString("IssuerIssTaxpayerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add in credit note.
        /// </summary>
        public static string lblAddCreditNote {
            get {
                return ResourceManager.GetString("lblAddCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string lblAmountCreditNote {
            get {
                return ResourceManager.GetString("lblAmountCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Totals.
        /// </summary>
        public static string lblCalculateTotals {
            get {
                return ResourceManager.GetString("lblCalculateTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFDI Use.
        /// </summary>
        public static string lblCFDIUse {
            get {
                return ResourceManager.GetString("lblCFDIUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit code to amount refund.
        /// </summary>
        public static string lblCodeAmountRefund {
            get {
                return ResourceManager.GetString("lblCodeAmountRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit code to tax refund.
        /// </summary>
        public static string lblCodeTaxRefund {
            get {
                return ResourceManager.GetString("lblCodeTaxRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string lblComments {
            get {
                return ResourceManager.GetString("lblComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string lblCurrency {
            get {
                return ResourceManager.GetString("lblCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUE - Pago en una sola exhibición.
        /// </summary>
        public static string lblDefaultPaymentMethod {
            get {
                return ResourceManager.GetString("lblDefaultPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string lblDetail {
            get {
                return ResourceManager.GetString("lblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount.
        /// </summary>
        public static string lblEmptyAmount {
            get {
                return ResourceManager.GetString("lblEmptyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Number.
        /// </summary>
        public static string lblIdNumber {
            get {
                return ResourceManager.GetString("lblIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Address.
        /// </summary>
        public static string lblIssuerAddress {
            get {
                return ResourceManager.GetString("lblIssuerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or Corporate Name.
        /// </summary>
        public static string lblIssuerCorporateName {
            get {
                return ResourceManager.GetString("lblIssuerCorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Issue.
        /// </summary>
        public static string lblIssuerPlaceofIssue {
            get {
                return ResourceManager.GetString("lblIssuerPlaceofIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string lblIssuerSerial {
            get {
                return ResourceManager.GetString("lblIssuerSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxpayer ID.
        /// </summary>
        public static string lblIssuerTaxpayerId {
            get {
                return ResourceManager.GetString("lblIssuerTaxpayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax regimen.
        /// </summary>
        public static string lblIssuerTaxRegimen {
            get {
                return ResourceManager.GetString("lblIssuerTaxRegimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last folio assigned for this serial has reached its maximum value.
        /// </summary>
        public static string lblLastFolioAssigned {
            get {
                return ResourceManager.GetString("lblLastFolioAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Condition.
        /// </summary>
        public static string lblPaymentCondition {
            get {
                return ResourceManager.GetString("lblPaymentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string lblPaymentMethod {
            get {
                return ResourceManager.GetString("lblPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string lblPaymentType {
            get {
                return ResourceManager.GetString("lblPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string lblProcessCreditNote {
            get {
                return ResourceManager.GetString("lblProcessCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product/Service Code.
        /// </summary>
        public static string lblProductServiceCode {
            get {
                return ResourceManager.GetString("lblProductServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string lblQuantity {
            get {
                return ResourceManager.GetString("lblQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Number.
        /// </summary>
        public static string lblReceiptNumber {
            get {
                return ResourceManager.GetString("lblReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or Corporate Name.
        /// </summary>
        public static string lblReceiverCorporateName {
            get {
                return ResourceManager.GetString("lblReceiverCorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblReceiverEmail {
            get {
                return ResourceManager.GetString("lblReceiverEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Residency.
        /// </summary>
        public static string lblReceiverFiscalAddress {
            get {
                return ResourceManager.GetString("lblReceiverFiscalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Identity Number.
        /// </summary>
        public static string lblReceiverFiscalIdentityNumber {
            get {
                return ResourceManager.GetString("lblReceiverFiscalIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxpayer ID.
        /// </summary>
        public static string lblReceiverTaxpayerId {
            get {
                return ResourceManager.GetString("lblReceiverTaxpayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related CFDI.
        /// </summary>
        public static string lblRelatedCFDI {
            get {
                return ResourceManager.GetString("lblRelatedCFDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04 - Sustitución de los CFDI previos.
        /// </summary>
        public static string lblRelationship04 {
            get {
                return ResourceManager.GetString("lblRelationship04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 - Nota de crédito de los documentos relacionados.
        /// </summary>
        public static string lblRelationshipDoc {
            get {
                return ResourceManager.GetString("lblRelationshipDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type.
        /// </summary>
        public static string lblRelationshipType {
            get {
                return ResourceManager.GetString("lblRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the required fields.
        /// </summary>
        public static string lblRequiredFields {
            get {
                return ResourceManager.GetString("lblRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitute and Cancel Fiscal Record.
        /// </summary>
        public static string lblSubstituteCancel {
            get {
                return ResourceManager.GetString("lblSubstituteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When creating a substitution credit note, the corresponding credits will not be created automatically. The credits created in the original credit note must be kept..
        /// </summary>
        public static string lblSubstitutionInstructions {
            get {
                return ResourceManager.GetString("lblSubstitutionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount.
        /// </summary>
        public static string lblTaxAmount {
            get {
                return ResourceManager.GetString("lblTaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Codes.
        /// </summary>
        public static string lblTitleCreditCode {
            get {
                return ResourceManager.GetString("lblTitleCreditCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Note.
        /// </summary>
        public static string lblTitleCreditNotes {
            get {
                return ResourceManager.GetString("lblTitleCreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Record.
        /// </summary>
        public static string lblTitleFiscalRecord {
            get {
                return ResourceManager.GetString("lblTitleFiscalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string lblTitleIssuer {
            get {
                return ResourceManager.GetString("lblTitleIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string lblTitleReceiver {
            get {
                return ResourceManager.GetString("lblTitleReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string lblTitleTotals {
            get {
                return ResourceManager.GetString("lblTitleTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string lblUnit {
            get {
                return ResourceManager.GetString("lblUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Amount.
        /// </summary>
        public static string lblUnitAmount {
            get {
                return ResourceManager.GetString("lblUnitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Code.
        /// </summary>
        public static string lblUnitCode {
            get {
                return ResourceManager.GetString("lblUnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID.
        /// </summary>
        public static string lblUUID {
            get {
                return ResourceManager.GetString("lblUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a taxpayer ID.
        /// </summary>
        public static string ReceiverTaxPayerIdRequired {
            get {
                return ResourceManager.GetString("ReceiverTaxPayerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a tax regimen.
        /// </summary>
        public static string ReceiverTaxRegimenRequired {
            get {
                return ResourceManager.GetString("ReceiverTaxRegimenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a tax address.
        /// </summary>
        public static string RecTaxAddressRequired {
            get {
                return ResourceManager.GetString("RecTaxAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit is maximum 20 characters.
        /// </summary>
        public static string UnitNameMaxLength {
            get {
                return ResourceManager.GetString("UnitNameMaxLength", resourceCulture);
            }
        }
    }
}
