//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicDegree {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Institution {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Institution() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicDegree.Institution", typeof(Institution).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Record.
        /// </summary>
        public static string lblAcademicRecord {
            get {
                return ResourceManager.GetString("lblAcademicRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Institution.
        /// </summary>
        public static string lblAddInstitution {
            get {
                return ResourceManager.GetString("lblAddInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code alredy exists.
        /// </summary>
        public static string lblCodeExists {
            get {
                return ResourceManager.GetString("lblCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Folio.
        /// </summary>
        public static string lblDegreeFolio {
            get {
                return ResourceManager.GetString("lblDegreeFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Folio already exists.
        /// </summary>
        public static string lblDegreeFolioExists {
            get {
                return ResourceManager.GetString("lblDegreeFolioExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built the default setting for the generation of Degree Folios, this field will be open for free modification in the generation of each degree..
        /// </summary>
        public static string lblDegreeFolioLabel {
            get {
                return ResourceManager.GetString("lblDegreeFolioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.Code.
        /// </summary>
        public static string lblEDInstCode {
            get {
                return ResourceManager.GetString("lblEDInstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Institution.
        /// </summary>
        public static string lblEditInstitution {
            get {
                return ResourceManager.GetString("lblEditInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Major Mapping.
        /// </summary>
        public static string lblEditMajorMapping {
            get {
                return ResourceManager.GetString("lblEditMajorMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Degree.
        /// </summary>
        public static string lblElectronicDegree {
            get {
                return ResourceManager.GetString("lblElectronicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equivalents.
        /// </summary>
        public static string lblEquivalents {
            get {
                return ResourceManager.GetString("lblEquivalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string lblErrorCode {
            get {
                return ResourceManager.GetString("lblErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Folio is required.
        /// </summary>
        public static string lblErrorDegreeFolio {
            get {
                return ResourceManager.GetString("lblErrorDegreeFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string lblErrorName {
            get {
                return ResourceManager.GetString("lblErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Folio.
        /// </summary>
        public static string lblFolio {
            get {
                return ResourceManager.GetString("lblFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio Tokens.
        /// </summary>
        public static string lblFolioTokens {
            get {
                return ResourceManager.GetString("lblFolioTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens selected in Degree Folio can creates Folios that exceds 40 caractheres and that is not allowed by SEP. .
        /// </summary>
        public static string lblFolioWarning {
            get {
                return ResourceManager.GetString("lblFolioWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string lblInstitution {
            get {
                return ResourceManager.GetString("lblInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.Code.
        /// </summary>
        public static string lblInstitutionCode {
            get {
                return ResourceManager.GetString("lblInstitutionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Code:.
        /// </summary>
        public static string lblInstitutionCodeMapping {
            get {
                return ResourceManager.GetString("lblInstitutionCodeMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.Name.
        /// </summary>
        public static string lblInstitutionMajor {
            get {
                return ResourceManager.GetString("lblInstitutionMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majors:.
        /// </summary>
        public static string lblInstitutionMajorsMapping {
            get {
                return ResourceManager.GetString("lblInstitutionMajorsMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.Name.
        /// </summary>
        public static string lblInstitutionName {
            get {
                return ResourceManager.GetString("lblInstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Name:.
        /// </summary>
        public static string lblInstitutionNameMapping {
            get {
                return ResourceManager.GetString("lblInstitutionNameMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions.
        /// </summary>
        public static string lblInstitutions {
            get {
                return ResourceManager.GetString("lblInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions-Majors Mapping.
        /// </summary>
        public static string lblInstitutionsMajorsMapping {
            get {
                return ResourceManager.GetString("lblInstitutionsMajorsMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Institutions.
        /// </summary>
        public static string lblInstitutionsNumber {
            get {
                return ResourceManager.GetString("lblInstitutionsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Majors.
        /// </summary>
        public static string lblMajors {
            get {
                return ResourceManager.GetString("lblMajors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Majors.
        /// </summary>
        public static string lblMajorsNumber {
            get {
                return ResourceManager.GetString("lblMajorsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Name already exists.
        /// </summary>
        public static string lblNameExists {
            get {
                return ResourceManager.GetString("lblNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Institutions to show, click the &quot;add&quot; button to create one..
        /// </summary>
        public static string lblNoInstitutions {
            get {
                return ResourceManager.GetString("lblNoInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Institutions to show.
        /// </summary>
        public static string lblNoInstitutionsMapping {
            get {
                return ResourceManager.GetString("lblNoInstitutionsMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Majors to show.
        /// </summary>
        public static string lblNoMajors {
            get {
                return ResourceManager.GetString("lblNoMajors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Campus Equivalents.
        /// </summary>
        public static string lblPCValue {
            get {
                return ResourceManager.GetString("lblPCValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerCampus Mapping.
        /// </summary>
        public static string lblPowerCampusMapping {
            get {
                return ResourceManager.GetString("lblPowerCampusMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialNum.
        /// </summary>
        public static string lblSerialNum {
            get {
                return ResourceManager.GetString("lblSerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string lblSetup {
            get {
                return ResourceManager.GetString("lblSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Signers.
        /// </summary>
        public static string lblSigners {
            get {
                return ResourceManager.GetString("lblSigners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.Curp.
        /// </summary>
        public static string lblStudentCurp {
            get {
                return ResourceManager.GetString("lblStudentCurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.FirstName.
        /// </summary>
        public static string lblStudentFirstName {
            get {
                return ResourceManager.GetString("lblStudentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.FirstSurname.
        /// </summary>
        public static string lblStudentFirstSurname {
            get {
                return ResourceManager.GetString("lblStudentFirstSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.PeopleId.
        /// </summary>
        public static string lblStudentPeopleId {
            get {
                return ResourceManager.GetString("lblStudentPeopleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.SecondSurname.
        /// </summary>
        public static string lblStudentSecondSurname {
            get {
                return ResourceManager.GetString("lblStudentSecondSurname", resourceCulture);
            }
        }
    }
}
