//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicDegree {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Major {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Major() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicDegree.Major", typeof(Major).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Major.
        /// </summary>
        public static string lblAddMajor {
            get {
                return ResourceManager.GetString("lblAddMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACHILLER TÉCNICO.
        /// </summary>
        public static string lblBachilleratoTecnico {
            get {
                return ResourceManager.GetString("lblBachilleratoTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lblCVE {
            get {
                return ResourceManager.GetString("lblCVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code, minimum 6 and maximum 7 characters..
        /// </summary>
        public static string lblCveInvalidLength {
            get {
                return ResourceManager.GetString("lblCveInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCTORADO.
        /// </summary>
        public static string lblDoctorado {
            get {
                return ResourceManager.GetString("lblDoctorado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Major.
        /// </summary>
        public static string lblEditMajor {
            get {
                return ResourceManager.GetString("lblEditMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        public static string lblEducationLevel {
            get {
                return ResourceManager.GetString("lblEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equivalents.
        /// </summary>
        public static string lblEquivalents {
            get {
                return ResourceManager.GetString("lblEquivalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVE is required.
        /// </summary>
        public static string lblErrorCVE {
            get {
                return ResourceManager.GetString("lblErrorCVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level is required.
        /// </summary>
        public static string lblErrorEducationLevel {
            get {
                return ResourceManager.GetString("lblErrorEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Base is required.
        /// </summary>
        public static string lblErrorLegalBaseId {
            get {
                return ResourceManager.GetString("lblErrorLegalBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Name is required.
        /// </summary>
        public static string lblErrorMajorName {
            get {
                return ResourceManager.GetString("lblErrorMajorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPECIALIDAD.
        /// </summary>
        public static string lblEspecialidad {
            get {
                return ResourceManager.GetString("lblEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code has already been used..
        /// </summary>
        public static string lblExistsCve {
            get {
                return ResourceManager.GetString("lblExistsCve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Institutions.
        /// </summary>
        public static string lblInstitutions {
            get {
                return ResourceManager.GetString("lblInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Base for Social Service.
        /// </summary>
        public static string lblLegalBaseCatalog {
            get {
                return ResourceManager.GetString("lblLegalBaseCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LICENCIATURA.
        /// </summary>
        public static string lblLicenciatura {
            get {
                return ResourceManager.GetString("lblLicenciatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAESTRIA.
        /// </summary>
        public static string lblMaestria {
            get {
                return ResourceManager.GetString("lblMaestria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string lblMajor {
            get {
                return ResourceManager.GetString("lblMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Name.
        /// </summary>
        public static string lblMajorName {
            get {
                return ResourceManager.GetString("lblMajorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majors.
        /// </summary>
        public static string lblMajors {
            get {
                return ResourceManager.GetString("lblMajors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no majors to show, click the Add button to start..
        /// </summary>
        public static string lblNoMajors {
            get {
                return ResourceManager.GetString("lblNoMajors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Campus Equivalents.
        /// </summary>
        public static string lblPowerCampusEq {
            get {
                return ResourceManager.GetString("lblPowerCampusEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Campus Mapping.
        /// </summary>
        public static string lblPowerCampusMapping {
            get {
                return ResourceManager.GetString("lblPowerCampusMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFESIONAL ASOCIADO.
        /// </summary>
        public static string lblProfesionalAsociado {
            get {
                return ResourceManager.GetString("lblProfesionalAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFESIONAL TÉCNICO.
        /// </summary>
        public static string lblProfesionalTecnico {
            get {
                return ResourceManager.GetString("lblProfesionalTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFESOR.
        /// </summary>
        public static string lblProfesor {
            get {
                return ResourceManager.GetString("lblProfesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVOE.
        /// </summary>
        public static string lblRvoe {
            get {
                return ResourceManager.GetString("lblRvoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected RVOE.
        /// </summary>
        public static string lblSelectedRvoe {
            get {
                return ResourceManager.GetString("lblSelectedRvoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÉCNICO.
        /// </summary>
        public static string lblTecnico {
            get {
                return ResourceManager.GetString("lblTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÉCNICO PROFESIONAL.
        /// </summary>
        public static string lblTecnicoProfesional {
            get {
                return ResourceManager.GetString("lblTecnicoProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÉCNICO SUPERIOR.
        /// </summary>
        public static string lblTecnicoSuperior {
            get {
                return ResourceManager.GetString("lblTecnicoSuperior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÉCNICO SUPERIOR UNIVERSITARIO.
        /// </summary>
        public static string lblTecnicoSuperiorUniv {
            get {
                return ResourceManager.GetString("lblTecnicoSuperiorUniv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TECNOLÓGICO.
        /// </summary>
        public static string lblTecnologico {
            get {
                return ResourceManager.GetString("lblTecnologico", resourceCulture);
            }
        }
    }
}
