//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicDegree {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Operations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Operations() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicDegree.Operations", typeof(Operations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string lblAccept {
            get {
                return ResourceManager.GetString("lblAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actions.
        /// </summary>
        public static string lblActions {
            get {
                return ResourceManager.GetString("lblActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authenticated.
        /// </summary>
        public static string lblAuthenticated {
            get {
                return ResourceManager.GetString("lblAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the reason for the cancelation of this Electronic Degree..
        /// </summary>
        public static string lblCancelationReason {
            get {
                return ResourceManager.GetString("lblCancelationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceled.
        /// </summary>
        public static string lblCanceled {
            get {
                return ResourceManager.GetString("lblCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel Electronic Degree.
        /// </summary>
        public static string lblCancelElectronicDegree {
            get {
                return ResourceManager.GetString("lblCancelElectronicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want delete this Electronic Degree?.
        /// </summary>
        public static string lblDeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("lblDeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Electronic Degree.
        /// </summary>
        public static string lblDeleteElectronicDegree {
            get {
                return ResourceManager.GetString("lblDeleteElectronicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download original string.
        /// </summary>
        public static string lblDownloadOriginalString {
            get {
                return ResourceManager.GetString("lblDownloadOriginalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download XML.
        /// </summary>
        public static string lblDownloadXml {
            get {
                return ResourceManager.GetString("lblDownloadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &quot;Reason&quot; is required..
        /// </summary>
        public static string lblErrorReason {
            get {
                return ResourceManager.GetString("lblErrorReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folio:.
        /// </summary>
        public static string lblFolio {
            get {
                return ResourceManager.GetString("lblFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generated.
        /// </summary>
        public static string lblGenerated {
            get {
                return ResourceManager.GetString("lblGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Electronic Degree..
        /// </summary>
        public static string lblInvalidElectronicDegree {
            get {
                return ResourceManager.GetString("lblInvalidElectronicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid request. Review the information for the current record and try again.
        /// </summary>
        public static string lblInvalidRequest {
            get {
                return ResourceManager.GetString("lblInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electronic Degree Operations.
        /// </summary>
        public static string lblOperationsElectronicDegree {
            get {
                return ResourceManager.GetString("lblOperationsElectronicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reason.
        /// </summary>
        public static string lblReason {
            get {
                return ResourceManager.GetString("lblReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rejected.
        /// </summary>
        public static string lblRejected {
            get {
                return ResourceManager.GetString("lblRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Results.
        /// </summary>
        public static string lblResults {
            get {
                return ResourceManager.GetString("lblResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select....
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string lblSend {
            get {
                return ResourceManager.GetString("lblSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent.
        /// </summary>
        public static string lblSent {
            get {
                return ResourceManager.GetString("lblSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The web service couldn&apos;t reached. Try again later.
        /// </summary>
        public static string lblServiceUnavailable {
            get {
                return ResourceManager.GetString("lblServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stamp &amp; Send.
        /// </summary>
        public static string lblStampSend {
            get {
                return ResourceManager.GetString("lblStampSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status:.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Student Name.
        /// </summary>
        public static string lblStudentName {
            get {
                return ResourceManager.GetString("lblStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XLS file was not processed. Review logs.
        /// </summary>
        public static string lblUnabletoProcessXls {
            get {
                return ResourceManager.GetString("lblUnabletoProcessXls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ZIP file was not processed. Review logs.
        /// </summary>
        public static string lblUnabletoProcessZip {
            get {
                return ResourceManager.GetString("lblUnabletoProcessZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Status.
        /// </summary>
        public static string lblUpdateStatus {
            get {
                return ResourceManager.GetString("lblUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        public static string lblView {
            get {
                return ResourceManager.GetString("lblView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Data.
        /// </summary>
        public static string lblViewData {
            get {
                return ResourceManager.GetString("lblViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
    }
}
