//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicDegree {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Operator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Operator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicDegree.Operator", typeof(Operator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Operator.
        /// </summary>
        public static string lblAddOperator {
            get {
                return ResourceManager.GetString("lblAddOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Visualization Permissions.
        /// </summary>
        public static string lblAddVisualizationPer {
            get {
                return ResourceManager.GetString("lblAddVisualizationPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string lblApply {
            get {
                return ResourceManager.GetString("lblApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Operator.
        /// </summary>
        public static string lblEditOperator {
            get {
                return ResourceManager.GetString("lblEditOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Signer.
        /// </summary>
        public static string lblFirstSigner {
            get {
                return ResourceManager.GetString("lblFirstSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string lblInstitution {
            get {
                return ResourceManager.GetString("lblInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions.
        /// </summary>
        public static string lblInstitutions {
            get {
                return ResourceManager.GetString("lblInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Position.
        /// </summary>
        public static string lblLaborPosition {
            get {
                return ResourceManager.GetString("lblLaborPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no operators to show, click the Add button to start..
        /// </summary>
        public static string lblNoOperators {
            get {
                return ResourceManager.GetString("lblNoOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To show Signers select an institution..
        /// </summary>
        public static string lblNoSigners {
            get {
                return ResourceManager.GetString("lblNoSigners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no signers assigned to this institution.
        /// </summary>
        public static string lblNoSignersInstitutions {
            get {
                return ResourceManager.GetString("lblNoSignersInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No visualization permissions given, click on the button to add.
        /// </summary>
        public static string lblNoVisualizationPer {
            get {
                return ResourceManager.GetString("lblNoVisualizationPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        public static string lblNumberId {
            get {
                return ResourceManager.GetString("lblNumberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Institutions.
        /// </summary>
        public static string lblNumberInstitution {
            get {
                return ResourceManager.GetString("lblNumberInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string lblOperator {
            get {
                return ResourceManager.GetString("lblOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator ID.
        /// </summary>
        public static string lblOperatorId {
            get {
                return ResourceManager.GetString("lblOperatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string lblOperators {
            get {
                return ResourceManager.GetString("lblOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string lblRemove {
            get {
                return ResourceManager.GetString("lblRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Visualization Permission.
        /// </summary>
        public static string lblRemoveVisualizationPer {
            get {
                return ResourceManager.GetString("lblRemoveVisualizationPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string lblSavedSuccesfull {
            get {
                return ResourceManager.GetString("lblSavedSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Operators to add Visualization Permissions..
        /// </summary>
        public static string lblSearchLegend {
            get {
                return ResourceManager.GetString("lblSearchLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Signer.
        /// </summary>
        public static string lblSecondSigner {
            get {
                return ResourceManager.GetString("lblSecondSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer.
        /// </summary>
        public static string lblSigner {
            get {
                return ResourceManager.GetString("lblSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Signer.
        /// </summary>
        public static string lblThirdSigner {
            get {
                return ResourceManager.GetString("lblThirdSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization Permissions.
        /// </summary>
        public static string lblVisualizationPer {
            get {
                return ResourceManager.GetString("lblVisualizationPer", resourceCulture);
            }
        }
    }
}
