//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicDegree {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Signer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Signer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicDegree.Signer", typeof(Signer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Record.
        /// </summary>
        public static string lblAcademicRecord {
            get {
                return ResourceManager.GetString("lblAcademicRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Signer.
        /// </summary>
        public static string lblAddSigner {
            get {
                return ResourceManager.GetString("lblAddSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curp.
        /// </summary>
        public static string lblCurp {
            get {
                return ResourceManager.GetString("lblCurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Signer.
        /// </summary>
        public static string lblEditSigner {
            get {
                return ResourceManager.GetString("lblEditSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Degree.
        /// </summary>
        public static string lblElectronicDegree {
            get {
                return ResourceManager.GetString("lblElectronicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Professional Title Abbreviation.
        /// </summary>
        public static string lblErrorAbbreviation {
            get {
                return ResourceManager.GetString("lblErrorAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Curp.
        /// </summary>
        public static string lblErrorCurp {
            get {
                return ResourceManager.GetString("lblErrorCurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Curp has already been used..
        /// </summary>
        public static string lblErrorCurpExists {
            get {
                return ResourceManager.GetString("lblErrorCurpExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a First Surname.
        /// </summary>
        public static string lblErrorFirstSurname {
            get {
                return ResourceManager.GetString("lblErrorFirstSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Labor Position.
        /// </summary>
        public static string lblErrorLaborPosition {
            get {
                return ResourceManager.GetString("lblErrorLaborPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Name.
        /// </summary>
        public static string lblErrorName {
            get {
                return ResourceManager.GetString("lblErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Second Surname.
        /// </summary>
        public static string lblErrorSecondSurname {
            get {
                return ResourceManager.GetString("lblErrorSecondSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Thumbprint.
        /// </summary>
        public static string lblErrorThumprint {
            get {
                return ResourceManager.GetString("lblErrorThumprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Thumprint it is invalid or has already been used..
        /// </summary>
        public static string lblErrorThumprintExists {
            get {
                return ResourceManager.GetString("lblErrorThumprintExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIEL.
        /// </summary>
        public static string lblFiel {
            get {
                return ResourceManager.GetString("lblFiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Surname.
        /// </summary>
        public static string lblFirstSurname {
            get {
                return ResourceManager.GetString("lblFirstSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string lblInactive {
            get {
                return ResourceManager.GetString("lblInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string lblInstitution {
            get {
                return ResourceManager.GetString("lblInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution´s Code.
        /// </summary>
        public static string lblInstitutionsCode {
            get {
                return ResourceManager.GetString("lblInstitutionsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Institutions.
        /// </summary>
        public static string lblInstitutionsName {
            get {
                return ResourceManager.GetString("lblInstitutionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Position.
        /// </summary>
        public static string lblLaborPosition {
            get {
                return ResourceManager.GetString("lblLaborPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor Position code.
        /// </summary>
        public static string lblLaborPositionCode {
            get {
                return ResourceManager.GetString("lblLaborPositionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no signers to show, click the Add button to start..
        /// </summary>
        public static string lblNoSigners {
            get {
                return ResourceManager.GetString("lblNoSigners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Title Abbreviation.
        /// </summary>
        public static string lblProfessionalTitleAbbreviation {
            get {
                return ResourceManager.GetString("lblProfessionalTitleAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Surname.
        /// </summary>
        public static string lblSecondSurname {
            get {
                return ResourceManager.GetString("lblSecondSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string lblSetup {
            get {
                return ResourceManager.GetString("lblSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signer.
        /// </summary>
        public static string lblSigner {
            get {
                return ResourceManager.GetString("lblSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signers.
        /// </summary>
        public static string lblSigners {
            get {
                return ResourceManager.GetString("lblSigners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbprint.
        /// </summary>
        public static string lblThumbprint {
            get {
                return ResourceManager.GetString("lblThumbprint", resourceCulture);
            }
        }
    }
}
