//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Views.FiscalRecords.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CancelGlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CancelGlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Views.FiscalRecords.App_LocalResources.CancelGlobalResource", typeof(CancelGlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete request.
        /// </summary>
        public static string btnDeleteRequest {
            get {
                return ResourceManager.GetString("btnDeleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string btnFinish {
            get {
                return ResourceManager.GetString("btnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string btnProcess {
            get {
                return ResourceManager.GetString("btnProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process and Finish.
        /// </summary>
        public static string btnProcessAndFinish {
            get {
                return ResourceManager.GetString("btnProcessAndFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprocess.
        /// </summary>
        public static string btnReprocess {
            get {
                return ResourceManager.GetString("btnReprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Global Invoice.
        /// </summary>
        public static string lblCancelGlobalInvoice {
            get {
                return ResourceManager.GetString("lblCancelGlobalInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string lblDetail {
            get {
                return ResourceManager.GetString("lblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        public static string lblEntryDate {
            get {
                return ResourceManager.GetString("lblEntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cancelation request has failed..
        /// </summary>
        public static string lblErrorAlertStep1 {
            get {
                return ResourceManager.GetString("lblErrorAlertStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Record.
        /// </summary>
        public static string lblFiscalRecord {
            get {
                return ResourceManager.GetString("lblFiscalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Invoice Cash Receipts.
        /// </summary>
        public static string lblGlobalInvoiceCashReceipts {
            get {
                return ResourceManager.GetString("lblGlobalInvoiceCashReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        public static string lblIdNumber {
            get {
                return ResourceManager.GetString("lblIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cancelation request has been sent. Wait for the provider&apos;s response to continue the process..
        /// </summary>
        public static string lblInfoAlertStep1 {
            get {
                return ResourceManager.GetString("lblInfoAlertStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the record is canceled, click next..
        /// </summary>
        public static string lblInstructionsCancelGlobalInvoice {
            get {
                return ResourceManager.GetString("lblInstructionsCancelGlobalInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Create to process an individual invoice for the receipt. The remaining receipts will be included in a new global invoice..
        /// </summary>
        public static string lblInstructionsCashReceipts {
            get {
                return ResourceManager.GetString("lblInstructionsCashReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Global Invoice.
        /// </summary>
        public static string lblNewGlobalInvoice {
            get {
                return ResourceManager.GetString("lblNewGlobalInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invoice.
        /// </summary>
        public static string lblNewInvoice {
            get {
                return ResourceManager.GetString("lblNewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invoices.
        /// </summary>
        public static string lblNewInvoices {
            get {
                return ResourceManager.GetString("lblNewInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no receipts left for a global invoice..
        /// </summary>
        public static string lblNoReceiptsLeft {
            get {
                return ResourceManager.GetString("lblNoReceiptsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string lblOrganization {
            get {
                return ResourceManager.GetString("lblOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string lblPeople {
            get {
                return ResourceManager.GetString("lblPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People/Organization ID.
        /// </summary>
        public static string lblPeopleOrgId {
            get {
                return ResourceManager.GetString("lblPeopleOrgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product/Service code.
        /// </summary>
        public static string lblProductServiceCode {
            get {
                return ResourceManager.GetString("lblProductServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string lblQuantity {
            get {
                return ResourceManager.GetString("lblQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string lblReceipt {
            get {
                return ResourceManager.GetString("lblReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Number.
        /// </summary>
        public static string lblReceiptNumber {
            get {
                return ResourceManager.GetString("lblReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject to Tax.
        /// </summary>
        public static string lblSubjectToTax {
            get {
                return ResourceManager.GetString("lblSubjectToTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount.
        /// </summary>
        public static string lblTaxAmount {
            get {
                return ResourceManager.GetString("lblTaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Fiscal Record.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string lblUnit {
            get {
                return ResourceManager.GetString("lblUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Amount.
        /// </summary>
        public static string lblUnitAmount {
            get {
                return ResourceManager.GetString("lblUnitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Code.
        /// </summary>
        public static string lblUnitCode {
            get {
                return ResourceManager.GetString("lblUnitCode", resourceCulture);
            }
        }
    }
}
