//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Views.FiscalRecords.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Views.FiscalRecords.App_LocalResources.CreateResource", typeof(CreateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process and Cancel.
        /// </summary>
        public static string btnProcessCancel {
            get {
                return ResourceManager.GetString("btnProcessCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CFDI Use.
        /// </summary>
        public static string CFDI {
            get {
                return ResourceManager.GetString("CFDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a CFDI use..
        /// </summary>
        public static string CFDIRequired {
            get {
                return ResourceManager.GetString("CFDIRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a charge description.
        /// </summary>
        public static string ChargeCreditDescRequired {
            get {
                return ResourceManager.GetString("ChargeCreditDescRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complement Currency.
        /// </summary>
        public static string ComplementCurrency {
            get {
                return ResourceManager.GetString("ComplementCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complement Payment Type.
        /// </summary>
        public static string ComplementPaymentType {
            get {
                return ResourceManager.GetString("ComplementPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a complement payment type.
        /// </summary>
        public static string ComplementPaymentTypeRequired {
            get {
                return ResourceManager.GetString("ComplementPaymentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name of the receiver must be &quot;PUBLICO EN GENERAL&quot;.
        /// </summary>
        public static string CorporateNameIncorrect {
            get {
                return ResourceManager.GetString("CorporateNameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Fiscal Record.
        /// </summary>
        public static string CreateFiscalRecord {
            get {
                return ResourceManager.GetString("CreateFiscalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please Select....
        /// </summary>
        public static string EmptyTaxPayerId {
            get {
                return ResourceManager.GetString("EmptyTaxPayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter an end date.
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a valid email address.
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while processing your request.
        /// </summary>
        public static string ErrorMessageResult {
            get {
                return ResourceManager.GetString("ErrorMessageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fiscal Record Type.
        /// </summary>
        public static string FiscalRecType {
            get {
                return ResourceManager.GetString("FiscalRecType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a frequency.
        /// </summary>
        public static string FrequencyRequired {
            get {
                return ResourceManager.GetString("FrequencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Number.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information for the Fiscal Record cannot contain | character..
        /// </summary>
        public static string InvalidCharacterMessage {
            get {
                return ResourceManager.GetString("InvalidCharacterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sub Total amount cannot be 0.
        /// </summary>
        public static string InvalidSubTotalAmount {
            get {
                return ResourceManager.GetString("InvalidSubTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Amount cannot be 0.
        /// </summary>
        public static string InvalidTotalAmount {
            get {
                return ResourceManager.GetString("InvalidTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an issuing address.
        /// </summary>
        public static string IssAddRequired {
            get {
                return ResourceManager.GetString("IssAddRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comments.
        /// </summary>
        public static string IssComments {
            get {
                return ResourceManager.GetString("IssComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currency.
        /// </summary>
        public static string IssCurrency {
            get {
                return ResourceManager.GetString("IssCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exchange Rate.
        /// </summary>
        public static string IssExchangeRate {
            get {
                return ResourceManager.GetString("IssExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issuing Address.
        /// </summary>
        public static string IssExpeditionAddr {
            get {
                return ResourceManager.GetString("IssExpeditionAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name or Corporate Name.
        /// </summary>
        public static string IssNameCorp {
            get {
                return ResourceManager.GetString("IssNameCorp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place of Issue.
        /// </summary>
        public static string IssPlaceIssue {
            get {
                return ResourceManager.GetString("IssPlaceIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a place of issue.
        /// </summary>
        public static string IssPlaceRequired {
            get {
                return ResourceManager.GetString("IssPlaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial.
        /// </summary>
        public static string IssSerial {
            get {
                return ResourceManager.GetString("IssSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a serial.
        /// </summary>
        public static string IssSerialRequired {
            get {
                return ResourceManager.GetString("IssSerialRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taxpayer ID.
        /// </summary>
        public static string IssTaxPayerID {
            get {
                return ResourceManager.GetString("IssTaxPayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a taxpayer ID.
        /// </summary>
        public static string IssTaxPIRequired {
            get {
                return ResourceManager.GetString("IssTaxPIRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Regimen.
        /// </summary>
        public static string IssTaxRegimen {
            get {
                return ResourceManager.GetString("IssTaxRegimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a tax regimen.
        /// </summary>
        public static string IssTaxRegRequired {
            get {
                return ResourceManager.GetString("IssTaxRegRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue Date.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue Date is required.
        /// </summary>
        public static string IssueDateRequired {
            get {
                return ResourceManager.GetString("IssueDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issuer.
        /// </summary>
        public static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issuer Taxpayer ID Origin Account.
        /// </summary>
        public static string IssuerTaxPayerIdOriginAccount {
            get {
                return ResourceManager.GetString("IssuerTaxPayerIdOriginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issuer Tax Payer Id Target Account.
        /// </summary>
        public static string IssuerTaxPayerIdTargetAccount {
            get {
                return ResourceManager.GetString("IssuerTaxPayerIdTargetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue Time.
        /// </summary>
        public static string IssueTime {
            get {
                return ResourceManager.GetString("IssueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Issue Time is required.
        /// </summary>
        public static string IssueTimeRequired {
            get {
                return ResourceManager.GetString("IssueTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculate totals.
        /// </summary>
        public static string lblCalculateTotals {
            get {
                return ResourceManager.GetString("lblCalculateTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        public static string lblDetail {
            get {
                return ResourceManager.GetString("lblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date is after end date..
        /// </summary>
        public static string lblErrorDatesRange {
            get {
                return ResourceManager.GetString("lblErrorDatesRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoice.
        /// </summary>
        public static string lblInvoice {
            get {
                return ResourceManager.GetString("lblInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last folio assigned for this serial has reached its maximum value.
        /// </summary>
        public static string lblLastFolioAssigned {
            get {
                return ResourceManager.GetString("lblLastFolioAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Invoice.
        /// </summary>
        public static string lblNewInvoice {
            get {
                return ResourceManager.GetString("lblNewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment type.
        /// </summary>
        public static string lblPaymentType {
            get {
                return ResourceManager.GetString("lblPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Related CFDI.
        /// </summary>
        public static string lblRelatedCFDI {
            get {
                return ResourceManager.GetString("lblRelatedCFDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Related UUID.
        /// </summary>
        public static string lblRelatedUUID {
            get {
                return ResourceManager.GetString("lblRelatedUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relationship type.
        /// </summary>
        public static string lblRelationType {
            get {
                return ResourceManager.GetString("lblRelationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Receipts.
        /// </summary>
        public static string lblSearchReceipts {
            get {
                return ResourceManager.GetString("lblSearchReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select....
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Session.
        /// </summary>
        public static string lblSession {
            get {
                return ResourceManager.GetString("lblSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Substitute and Cancel Fiscal Record.
        /// </summary>
        public static string lblSubstituteCancel {
            get {
                return ResourceManager.GetString("lblSubstituteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Substitute and Cancel Global Fiscal Record.
        /// </summary>
        public static string lblSubstituteCancelGlobal {
            get {
                return ResourceManager.GetString("lblSubstituteCancelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rate or Fee mapping is missing..
        /// </summary>
        public static string lblTaxMapping {
            get {
                return ResourceManager.GetString("lblTaxMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Term.
        /// </summary>
        public static string lblTerm {
            get {
                return ResourceManager.GetString("lblTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max Length is 255..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a month.
        /// </summary>
        public static string MonthRequired {
            get {
                return ResourceManager.GetString("MonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected Payment Type is the one in which the higher amount was received..
        /// </summary>
        public static string NotePaymentType {
            get {
                return ResourceManager.GetString("NotePaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origin Account.
        /// </summary>
        public static string OriginAccount {
            get {
                return ResourceManager.GetString("OriginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank Name.
        /// </summary>
        public static string OriginBankName {
            get {
                return ResourceManager.GetString("OriginBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Account Number.
        /// </summary>
        public static string PaymentAccNum {
            get {
                return ResourceManager.GetString("PaymentAccNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Certificate.
        /// </summary>
        public static string PaymentCertificate {
            get {
                return ResourceManager.GetString("PaymentCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Chain.
        /// </summary>
        public static string PaymentChain {
            get {
                return ResourceManager.GetString("PaymentChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Chain Type.
        /// </summary>
        public static string PaymentChainType {
            get {
                return ResourceManager.GetString("PaymentChainType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Condition.
        /// </summary>
        public static string PaymentCondition {
            get {
                return ResourceManager.GetString("PaymentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Date.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Method.
        /// </summary>
        public static string paymentMethodDescDefault {
            get {
                return ResourceManager.GetString("paymentMethodDescDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Signature.
        /// </summary>
        public static string PaymentSignature {
            get {
                return ResourceManager.GetString("PaymentSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment type mapping is missing..
        /// </summary>
        public static string PaymentTypeMissing {
            get {
                return ResourceManager.GetString("PaymentTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Address.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string preferredReceiverEmail {
            get {
                return ResourceManager.GetString("preferredReceiverEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product/Service Code.
        /// </summary>
        public static string ProductServiceCode {
            get {
                return ResourceManager.GetString("ProductServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product/Service and Unit Code mapping is missing..
        /// </summary>
        public static string ProductServiceCodeRequired {
            get {
                return ResourceManager.GetString("ProductServiceCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The use of CFDI for global invoices must be &quot;S01 - Sin efectos fiscales&quot;.
        /// </summary>
        public static string RecCfdiUsageIncorrect {
            get {
                return ResourceManager.GetString("RecCfdiUsageIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receipt Number.
        /// </summary>
        public static string receiptNumber {
            get {
                return ResourceManager.GetString("receiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no receipts to include in the Fiscal Record..
        /// </summary>
        public static string ReceiptsToInvoiceEmpty {
            get {
                return ResourceManager.GetString("ReceiptsToInvoiceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receiver.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name or Corporate Name.
        /// </summary>
        public static string ReceiverCorpName {
            get {
                return ResourceManager.GetString("ReceiverCorpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter an email.
        /// </summary>
        public static string ReceiverEmail {
            get {
                return ResourceManager.GetString("ReceiverEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a valid email.
        /// </summary>
        public static string ReceiverEmailValidate {
            get {
                return ResourceManager.GetString("ReceiverEmailValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fiscal Residency.
        /// </summary>
        public static string ReceiverFiscalAddress {
            get {
                return ResourceManager.GetString("ReceiverFiscalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Address is required.
        /// </summary>
        public static string ReceiverFiscalAddressRequired {
            get {
                return ResourceManager.GetString("ReceiverFiscalAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fiscal Identity Number.
        /// </summary>
        public static string ReceiverFiscalID {
            get {
                return ResourceManager.GetString("ReceiverFiscalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax address must match the fiscal address of the issuer.
        /// </summary>
        public static string RecTaxAddressIncorrect {
            get {
                return ResourceManager.GetString("RecTaxAddressIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Regimen.
        /// </summary>
        public static string RecTaxRegimen {
            get {
                return ResourceManager.GetString("RecTaxRegimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The tax regimen for global invoices must be &quot;616 - Sin obligaciones fiscales&quot;.
        /// </summary>
        public static string RecTaxRegimenIncorrect {
            get {
                return ResourceManager.GetString("RecTaxRegimenIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a tax regimen.
        /// </summary>
        public static string RecTaxRegimenRequired {
            get {
                return ResourceManager.GetString("RecTaxRegimenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify required Fields.
        /// </summary>
        public static string RequiredFieldsMessage {
            get {
                return ResourceManager.GetString("RequiredFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a tax address.
        /// </summary>
        public static string RequiredPostalCode {
            get {
                return ResourceManager.GetString("RequiredPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a CFDI use.
        /// </summary>
        public static string RequiredPreferredCFDIUsageCode {
            get {
                return ResourceManager.GetString("RequiredPreferredCFDIUsageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a valid Serial Number.
        /// </summary>
        public static string SerialError {
            get {
                return ResourceManager.GetString("SerialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a start date.
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fiscal Record.
        /// </summary>
        public static string SubHeaderFiscalRecord {
            get {
                return ResourceManager.GetString("SubHeaderFiscalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Receipt complement.
        /// </summary>
        public static string SubHeaderPaymentReceipt {
            get {
                return ResourceManager.GetString("SubHeaderPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject to Tax.
        /// </summary>
        public static string SubjectToTax {
            get {
                return ResourceManager.GetString("SubjectToTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sub Total.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target Account.
        /// </summary>
        public static string TargetAccount {
            get {
                return ResourceManager.GetString("TargetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Address.
        /// </summary>
        public static string TaxAddress {
            get {
                return ResourceManager.GetString("TaxAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a tax address.
        /// </summary>
        public static string TaxAddressRequired {
            get {
                return ResourceManager.GetString("TaxAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Amount.
        /// </summary>
        public static string TaxAmount {
            get {
                return ResourceManager.GetString("TaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Taxpayer ID.
        /// </summary>
        public static string TaxpayerID {
            get {
                return ResourceManager.GetString("TaxpayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a valid taxpayer ID.
        /// </summary>
        public static string TaxPayerIdInvalid {
            get {
                return ResourceManager.GetString("TaxPayerIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a taxpayer ID.
        /// </summary>
        public static string TaxPayerIdRequired {
            get {
                return ResourceManager.GetString("TaxPayerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Fiscal Record.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Global Fiscal Record.
        /// </summary>
        public static string TitleGlobal {
            get {
                return ResourceManager.GetString("TitleGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Payment Receipt.
        /// </summary>
        public static string TitlePaymentReceipt {
            get {
                return ResourceManager.GetString("TitlePaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Transferred Taxes.
        /// </summary>
        public static string TotalTransferredTaxes {
            get {
                return ResourceManager.GetString("TotalTransferredTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transaction Number.
        /// </summary>
        public static string TransactionNumber {
            get {
                return ResourceManager.GetString("TransactionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit Amount.
        /// </summary>
        public static string UnitAmount {
            get {
                return ResourceManager.GetString("UnitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit Code.
        /// </summary>
        public static string UnitCode {
            get {
                return ResourceManager.GetString("UnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit is maximum 20 characters.
        /// </summary>
        public static string UnitNameMaxLength {
            get {
                return ResourceManager.GetString("UnitNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string ViewButton {
            get {
                return ResourceManager.GetString("ViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a you@email.com.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
    }
}
