//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Views.FiscalRecords.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Related {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Related() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Views.FiscalRecords.App_LocalResources.Related", typeof(Related).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related fiscal records.
        /// </summary>
        public static string lblChildsSection {
            get {
                return ResourceManager.GetString("lblChildsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string lblCreditNote {
            get {
                return ResourceManager.GetString("lblCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Notes (Outcomes).
        /// </summary>
        public static string lblCreditNotes {
            get {
                return ResourceManager.GetString("lblCreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other credit notes from the same invoice (Outcomes).
        /// </summary>
        public static string lblCreditNotesInvoice {
            get {
                return ResourceManager.GetString("lblCreditNotesInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other credit notes from the same PPD (Outcomes).
        /// </summary>
        public static string lblCreditNotesPDD {
            get {
                return ResourceManager.GetString("lblCreditNotesPDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string lblDetail {
            get {
                return ResourceManager.GetString("lblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string lblFiscalRecord {
            get {
                return ResourceManager.GetString("lblFiscalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Record Type.
        /// </summary>
        public static string lblFiscalRecordType {
            get {
                return ResourceManager.GetString("lblFiscalRecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Fiscal Record.
        /// </summary>
        public static string lblOrigin {
            get {
                return ResourceManager.GetString("lblOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Record Parent.
        /// </summary>
        public static string lblParentSection {
            get {
                return ResourceManager.GetString("lblParentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Receipt Supplement (Payment).
        /// </summary>
        public static string lblPaymentReceipt {
            get {
                return ResourceManager.GetString("lblPaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other payment receipt supplements from the same PPD (Payments).
        /// </summary>
        public static string lblPaymentReceipts2 {
            get {
                return ResourceManager.GetString("lblPaymentReceipts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type.
        /// </summary>
        public static string lblRelationshipType {
            get {
                return ResourceManager.GetString("lblRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Records Siblings.
        /// </summary>
        public static string lblSiblingsSection {
            get {
                return ResourceManager.GetString("lblSiblingsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Fiscal Record or PPD (Income).
        /// </summary>
        public static string lblSupplement {
            get {
                return ResourceManager.GetString("lblSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Records Supplement.
        /// </summary>
        public static string lblSupplementChildsSection {
            get {
                return ResourceManager.GetString("lblSupplementChildsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Receipt Supplements (Payments).
        /// </summary>
        public static string lblSupplementRelated {
            get {
                return ResourceManager.GetString("lblSupplementRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustitution of previous CFDI.
        /// </summary>
        public static string lblSustitution {
            get {
                return ResourceManager.GetString("lblSustitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Fiscal Records.
        /// </summary>
        public static string lblTitleRelated {
            get {
                return ResourceManager.GetString("lblTitleRelated", resourceCulture);
            }
        }
    }
}
