// --------------------------------------------------------------------
// <copyright file="Reference.cs" company="Ellucian">
//     Copyright 2017 - 2021 Ellucian Company L.P. and its affiliates.
// </copyright>
// --------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerCampus.Business.SepService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", ConfigurationName="SepService.TitulosPortType")]
    public interface TitulosPortType {
        
        // CODEGEN: Generating message contract since the operation cargaTituloElectronico is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PowerCampus.Business.SepService.cargaTituloElectronicoResponse1 cargaTituloElectronico(PowerCampus.Business.SepService.cargaTituloElectronicoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PowerCampus.Business.SepService.cargaTituloElectronicoResponse1> cargaTituloElectronicoAsync(PowerCampus.Business.SepService.cargaTituloElectronicoRequest1 request);
        
        // CODEGEN: Generating message contract since the operation consultaProcesoTituloElectronico is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PowerCampus.Business.SepService.consultaProcesoTituloElectronicoResponse1 consultaProcesoTituloElectronico(PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PowerCampus.Business.SepService.consultaProcesoTituloElectronicoResponse1> consultaProcesoTituloElectronicoAsync(PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest1 request);
        
        // CODEGEN: Generating message contract since the operation descargaTituloElectronico is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PowerCampus.Business.SepService.descargaTituloElectronicoResponse1 descargaTituloElectronico(PowerCampus.Business.SepService.descargaTituloElectronicoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PowerCampus.Business.SepService.descargaTituloElectronicoResponse1> descargaTituloElectronicoAsync(PowerCampus.Business.SepService.descargaTituloElectronicoRequest1 request);
        
        // CODEGEN: Generating message contract since the operation cancelaTituloElectronico is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PowerCampus.Business.SepService.cancelaTituloElectronicoResponse1 cancelaTituloElectronico(PowerCampus.Business.SepService.cancelaTituloElectronicoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PowerCampus.Business.SepService.cancelaTituloElectronicoResponse1> cancelaTituloElectronicoAsync(PowerCampus.Business.SepService.cancelaTituloElectronicoRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cargaTituloElectronicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreArchivoField;
        
        private byte[] archivoBase64Field;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
                this.RaisePropertyChanged("nombreArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] archivoBase64 {
            get {
                return this.archivoBase64Field;
            }
            set {
                this.archivoBase64Field = value;
                this.RaisePropertyChanged("archivoBase64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class autenticacionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cargaTituloElectronicoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargaTituloElectronicoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public PowerCampus.Business.SepService.cargaTituloElectronicoRequest cargaTituloElectronicoRequest;
        
        public cargaTituloElectronicoRequest1() {
        }
        
        public cargaTituloElectronicoRequest1(PowerCampus.Business.SepService.cargaTituloElectronicoRequest cargaTituloElectronicoRequest) {
            this.cargaTituloElectronicoRequest = cargaTituloElectronicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargaTituloElectronicoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public PowerCampus.Business.SepService.cargaTituloElectronicoResponse cargaTituloElectronicoResponse;
        
        public cargaTituloElectronicoResponse1() {
        }
        
        public cargaTituloElectronicoResponse1(PowerCampus.Business.SepService.cargaTituloElectronicoResponse cargaTituloElectronicoResponse) {
            this.cargaTituloElectronicoResponse = cargaTituloElectronicoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class consultaProcesoTituloElectronicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class consultaProcesoTituloElectronicoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private short estatusLoteField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short estatusLote {
            get {
                return this.estatusLoteField;
            }
            set {
                this.estatusLoteField = value;
                this.RaisePropertyChanged("estatusLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaProcesoTituloElectronicoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest consultaProcesoTituloElectronicoRequest;
        
        public consultaProcesoTituloElectronicoRequest1() {
        }
        
        public consultaProcesoTituloElectronicoRequest1(PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest consultaProcesoTituloElectronicoRequest) {
            this.consultaProcesoTituloElectronicoRequest = consultaProcesoTituloElectronicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaProcesoTituloElectronicoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public PowerCampus.Business.SepService.consultaProcesoTituloElectronicoResponse consultaProcesoTituloElectronicoResponse;
        
        public consultaProcesoTituloElectronicoResponse1() {
        }
        
        public consultaProcesoTituloElectronicoResponse1(PowerCampus.Business.SepService.consultaProcesoTituloElectronicoResponse consultaProcesoTituloElectronicoResponse) {
            this.consultaProcesoTituloElectronicoResponse = consultaProcesoTituloElectronicoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class descargaTituloElectronicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class descargaTituloElectronicoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private string mensajeField;
        
        private byte[] titulosBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] titulosBase64 {
            get {
                return this.titulosBase64Field;
            }
            set {
                this.titulosBase64Field = value;
                this.RaisePropertyChanged("titulosBase64");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargaTituloElectronicoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public PowerCampus.Business.SepService.descargaTituloElectronicoRequest descargaTituloElectronicoRequest;
        
        public descargaTituloElectronicoRequest1() {
        }
        
        public descargaTituloElectronicoRequest1(PowerCampus.Business.SepService.descargaTituloElectronicoRequest descargaTituloElectronicoRequest) {
            this.descargaTituloElectronicoRequest = descargaTituloElectronicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargaTituloElectronicoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public PowerCampus.Business.SepService.descargaTituloElectronicoResponse descargaTituloElectronicoResponse;
        
        public descargaTituloElectronicoResponse1() {
        }
        
        public descargaTituloElectronicoResponse1(PowerCampus.Business.SepService.descargaTituloElectronicoResponse descargaTituloElectronicoResponse) {
            this.descargaTituloElectronicoResponse = descargaTituloElectronicoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cancelaTituloElectronicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string folioControlField;
        
        private string motCancelacionField;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string folioControl {
            get {
                return this.folioControlField;
            }
            set {
                this.folioControlField = value;
                this.RaisePropertyChanged("folioControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string motCancelacion {
            get {
                return this.motCancelacionField;
            }
            set {
                this.motCancelacionField = value;
                this.RaisePropertyChanged("motCancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cancelaTituloElectronicoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelaTituloElectronicoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public PowerCampus.Business.SepService.cancelaTituloElectronicoRequest cancelaTituloElectronicoRequest;
        
        public cancelaTituloElectronicoRequest1() {
        }
        
        public cancelaTituloElectronicoRequest1(PowerCampus.Business.SepService.cancelaTituloElectronicoRequest cancelaTituloElectronicoRequest) {
            this.cancelaTituloElectronicoRequest = cancelaTituloElectronicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelaTituloElectronicoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public PowerCampus.Business.SepService.cancelaTituloElectronicoResponse cancelaTituloElectronicoResponse;
        
        public cancelaTituloElectronicoResponse1() {
        }
        
        public cancelaTituloElectronicoResponse1(PowerCampus.Business.SepService.cancelaTituloElectronicoResponse cancelaTituloElectronicoResponse) {
            this.cancelaTituloElectronicoResponse = cancelaTituloElectronicoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TitulosPortTypeChannel : PowerCampus.Business.SepService.TitulosPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TitulosPortTypeClient : System.ServiceModel.ClientBase<PowerCampus.Business.SepService.TitulosPortType>, PowerCampus.Business.SepService.TitulosPortType {
        
        public TitulosPortTypeClient() {
        }
        
        public TitulosPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TitulosPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TitulosPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TitulosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PowerCampus.Business.SepService.cargaTituloElectronicoResponse1 PowerCampus.Business.SepService.TitulosPortType.cargaTituloElectronico(PowerCampus.Business.SepService.cargaTituloElectronicoRequest1 request) {
            return base.Channel.cargaTituloElectronico(request);
        }
        
        public PowerCampus.Business.SepService.cargaTituloElectronicoResponse cargaTituloElectronico(PowerCampus.Business.SepService.cargaTituloElectronicoRequest cargaTituloElectronicoRequest) {
            PowerCampus.Business.SepService.cargaTituloElectronicoRequest1 inValue = new PowerCampus.Business.SepService.cargaTituloElectronicoRequest1();
            inValue.cargaTituloElectronicoRequest = cargaTituloElectronicoRequest;
            PowerCampus.Business.SepService.cargaTituloElectronicoResponse1 retVal = ((PowerCampus.Business.SepService.TitulosPortType)(this)).cargaTituloElectronico(inValue);
            return retVal.cargaTituloElectronicoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PowerCampus.Business.SepService.cargaTituloElectronicoResponse1> PowerCampus.Business.SepService.TitulosPortType.cargaTituloElectronicoAsync(PowerCampus.Business.SepService.cargaTituloElectronicoRequest1 request) {
            return base.Channel.cargaTituloElectronicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PowerCampus.Business.SepService.cargaTituloElectronicoResponse1> cargaTituloElectronicoAsync(PowerCampus.Business.SepService.cargaTituloElectronicoRequest cargaTituloElectronicoRequest) {
            PowerCampus.Business.SepService.cargaTituloElectronicoRequest1 inValue = new PowerCampus.Business.SepService.cargaTituloElectronicoRequest1();
            inValue.cargaTituloElectronicoRequest = cargaTituloElectronicoRequest;
            return ((PowerCampus.Business.SepService.TitulosPortType)(this)).cargaTituloElectronicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PowerCampus.Business.SepService.consultaProcesoTituloElectronicoResponse1 PowerCampus.Business.SepService.TitulosPortType.consultaProcesoTituloElectronico(PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest1 request) {
            return base.Channel.consultaProcesoTituloElectronico(request);
        }
        
        public PowerCampus.Business.SepService.consultaProcesoTituloElectronicoResponse consultaProcesoTituloElectronico(PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest consultaProcesoTituloElectronicoRequest) {
            PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest1 inValue = new PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest1();
            inValue.consultaProcesoTituloElectronicoRequest = consultaProcesoTituloElectronicoRequest;
            PowerCampus.Business.SepService.consultaProcesoTituloElectronicoResponse1 retVal = ((PowerCampus.Business.SepService.TitulosPortType)(this)).consultaProcesoTituloElectronico(inValue);
            return retVal.consultaProcesoTituloElectronicoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PowerCampus.Business.SepService.consultaProcesoTituloElectronicoResponse1> PowerCampus.Business.SepService.TitulosPortType.consultaProcesoTituloElectronicoAsync(PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest1 request) {
            return base.Channel.consultaProcesoTituloElectronicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PowerCampus.Business.SepService.consultaProcesoTituloElectronicoResponse1> consultaProcesoTituloElectronicoAsync(PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest consultaProcesoTituloElectronicoRequest) {
            PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest1 inValue = new PowerCampus.Business.SepService.consultaProcesoTituloElectronicoRequest1();
            inValue.consultaProcesoTituloElectronicoRequest = consultaProcesoTituloElectronicoRequest;
            return ((PowerCampus.Business.SepService.TitulosPortType)(this)).consultaProcesoTituloElectronicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PowerCampus.Business.SepService.descargaTituloElectronicoResponse1 PowerCampus.Business.SepService.TitulosPortType.descargaTituloElectronico(PowerCampus.Business.SepService.descargaTituloElectronicoRequest1 request) {
            return base.Channel.descargaTituloElectronico(request);
        }
        
        public PowerCampus.Business.SepService.descargaTituloElectronicoResponse descargaTituloElectronico(PowerCampus.Business.SepService.descargaTituloElectronicoRequest descargaTituloElectronicoRequest) {
            PowerCampus.Business.SepService.descargaTituloElectronicoRequest1 inValue = new PowerCampus.Business.SepService.descargaTituloElectronicoRequest1();
            inValue.descargaTituloElectronicoRequest = descargaTituloElectronicoRequest;
            PowerCampus.Business.SepService.descargaTituloElectronicoResponse1 retVal = ((PowerCampus.Business.SepService.TitulosPortType)(this)).descargaTituloElectronico(inValue);
            return retVal.descargaTituloElectronicoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PowerCampus.Business.SepService.descargaTituloElectronicoResponse1> PowerCampus.Business.SepService.TitulosPortType.descargaTituloElectronicoAsync(PowerCampus.Business.SepService.descargaTituloElectronicoRequest1 request) {
            return base.Channel.descargaTituloElectronicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PowerCampus.Business.SepService.descargaTituloElectronicoResponse1> descargaTituloElectronicoAsync(PowerCampus.Business.SepService.descargaTituloElectronicoRequest descargaTituloElectronicoRequest) {
            PowerCampus.Business.SepService.descargaTituloElectronicoRequest1 inValue = new PowerCampus.Business.SepService.descargaTituloElectronicoRequest1();
            inValue.descargaTituloElectronicoRequest = descargaTituloElectronicoRequest;
            return ((PowerCampus.Business.SepService.TitulosPortType)(this)).descargaTituloElectronicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PowerCampus.Business.SepService.cancelaTituloElectronicoResponse1 PowerCampus.Business.SepService.TitulosPortType.cancelaTituloElectronico(PowerCampus.Business.SepService.cancelaTituloElectronicoRequest1 request) {
            return base.Channel.cancelaTituloElectronico(request);
        }
        
        public PowerCampus.Business.SepService.cancelaTituloElectronicoResponse cancelaTituloElectronico(PowerCampus.Business.SepService.cancelaTituloElectronicoRequest cancelaTituloElectronicoRequest) {
            PowerCampus.Business.SepService.cancelaTituloElectronicoRequest1 inValue = new PowerCampus.Business.SepService.cancelaTituloElectronicoRequest1();
            inValue.cancelaTituloElectronicoRequest = cancelaTituloElectronicoRequest;
            PowerCampus.Business.SepService.cancelaTituloElectronicoResponse1 retVal = ((PowerCampus.Business.SepService.TitulosPortType)(this)).cancelaTituloElectronico(inValue);
            return retVal.cancelaTituloElectronicoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PowerCampus.Business.SepService.cancelaTituloElectronicoResponse1> PowerCampus.Business.SepService.TitulosPortType.cancelaTituloElectronicoAsync(PowerCampus.Business.SepService.cancelaTituloElectronicoRequest1 request) {
            return base.Channel.cancelaTituloElectronicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PowerCampus.Business.SepService.cancelaTituloElectronicoResponse1> cancelaTituloElectronicoAsync(PowerCampus.Business.SepService.cancelaTituloElectronicoRequest cancelaTituloElectronicoRequest) {
            PowerCampus.Business.SepService.cancelaTituloElectronicoRequest1 inValue = new PowerCampus.Business.SepService.cancelaTituloElectronicoRequest1();
            inValue.cancelaTituloElectronicoRequest = cancelaTituloElectronicoRequest;
            return ((PowerCampus.Business.SepService.TitulosPortType)(this)).cancelaTituloElectronicoAsync(inValue);
        }
    }
}
