//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicCertificate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcademicPlan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcademicPlan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicCertificate.AcademicPlan", typeof(AcademicPlan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Plan.
        /// </summary>
        public static string lblAcademicPlan {
            get {
                return ResourceManager.GetString("lblAcademicPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Record.
        /// </summary>
        public static string lblAcademicRecord {
            get {
                return ResourceManager.GetString("lblAcademicRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        public static string lblCampus {
            get {
                return ResourceManager.GetString("lblCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        public static string lblClearFilters {
            get {
                return ResourceManager.GetString("lblClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course mapping.
        /// </summary>
        public static string lblCourseMapping {
            get {
                return ResourceManager.GetString("lblCourseMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Certificate.
        /// </summary>
        public static string lblElectronicCertificate {
            get {
                return ResourceManager.GetString("lblElectronicCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Date.
        /// </summary>
        public static string lblIssuingDate {
            get {
                return ResourceManager.GetString("lblIssuingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major ID.
        /// </summary>
        public static string lblMajorId {
            get {
                return ResourceManager.GetString("lblMajorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matriculation Term.
        /// </summary>
        public static string lblMatricTerm {
            get {
                return ResourceManager.GetString("lblMatricTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matriculation Year.
        /// </summary>
        public static string lblMatricYear {
            get {
                return ResourceManager.GetString("lblMatricYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Grade.
        /// </summary>
        public static string lblMaximumGrade {
            get {
                return ResourceManager.GetString("lblMaximumGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Grade.
        /// </summary>
        public static string lblMinimumGrade {
            get {
                return ResourceManager.GetString("lblMinimumGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Passing Grade.
        /// </summary>
        public static string lblMinPassingGrade {
            get {
                return ResourceManager.GetString("lblMinPassingGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string lblProgram {
            get {
                return ResourceManager.GetString("lblProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string lblPrograms {
            get {
                return ResourceManager.GetString("lblPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string lblResults {
            get {
                return ResourceManager.GetString("lblResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVOE.
        /// </summary>
        public static string lblRvoe {
            get {
                return ResourceManager.GetString("lblRvoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string lblSetup {
            get {
                return ResourceManager.GetString("lblSetup", resourceCulture);
            }
        }
    }
}
