//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicCertificate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Generate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicCertificate.Generate", typeof(Generate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Records.
        /// </summary>
        public static string lblAcademicRecords {
            get {
                return ResourceManager.GetString("lblAcademicRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept and Validate.
        /// </summary>
        public static string lblAcceptValidate {
            get {
                return ResourceManager.GetString("lblAcceptValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Courses.
        /// </summary>
        public static string lblAddCourses {
            get {
                return ResourceManager.GetString("lblAddCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string lblApply {
            get {
                return ResourceManager.GetString("lblApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Courses.
        /// </summary>
        public static string lblAsignedCourses {
            get {
                return ResourceManager.GetString("lblAsignedCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned:.
        /// </summary>
        public static string lblAssignedPreview {
            get {
                return ResourceManager.GetString("lblAssignedPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string lblAverage {
            get {
                return ResourceManager.GetString("lblAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average:.
        /// </summary>
        public static string lblAveragePreview {
            get {
                return ResourceManager.GetString("lblAveragePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string lblBirthDate {
            get {
                return ResourceManager.GetString("lblBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth:.
        /// </summary>
        public static string lblBirthDatePreview {
            get {
                return ResourceManager.GetString("lblBirthDatePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        public static string lblCampus {
            get {
                return ResourceManager.GetString("lblCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus SEP Code field has not been mapped in the institution-campus setup.
        /// </summary>
        public static string lblCampusCodeConflict {
            get {
                return ResourceManager.GetString("lblCampusCodeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus ID:.
        /// </summary>
        public static string lblCampusIdPreview {
            get {
                return ResourceManager.GetString("lblCampusIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus Name.
        /// </summary>
        public static string lblCampusName {
            get {
                return ResourceManager.GetString("lblCampusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus:.
        /// </summary>
        public static string lblCampusPreview {
            get {
                return ResourceManager.GetString("lblCampusPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus SEP ID.
        /// </summary>
        public static string lblCampusSepId {
            get {
                return ResourceManager.GetString("lblCampusSepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Type.
        /// </summary>
        public static string lblCertificationType {
            get {
                return ResourceManager.GetString("lblCertificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Type ID:.
        /// </summary>
        public static string lblCertificationTypeIdPreview {
            get {
                return ResourceManager.GetString("lblCertificationTypeIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Type:.
        /// </summary>
        public static string lblCertificationTypePreview {
            get {
                return ResourceManager.GetString("lblCertificationTypePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string lblContinue {
            get {
                return ResourceManager.GetString("lblContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string lblControl {
            get {
                return ResourceManager.GetString("lblControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Course.
        /// </summary>
        public static string lblCourse {
            get {
                return ResourceManager.GetString("lblCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string lblCourses {
            get {
                return ResourceManager.GetString("lblCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapping of the academic plan courses is not complete..
        /// </summary>
        public static string lblCoursesMappingConflict {
            get {
                return ResourceManager.GetString("lblCoursesMappingConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string lblCredits {
            get {
                return ResourceManager.GetString("lblCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits*.
        /// </summary>
        public static string lblCreditsRequired {
            get {
                return ResourceManager.GetString("lblCreditsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Type:.
        /// </summary>
        public static string lblCreditType {
            get {
                return ResourceManager.GetString("lblCreditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURP.
        /// </summary>
        public static string lblCurp {
            get {
                return ResourceManager.GetString("lblCurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURP:.
        /// </summary>
        public static string lblCurpPreview {
            get {
                return ResourceManager.GetString("lblCurpPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string lblCycle {
            get {
                return ResourceManager.GetString("lblCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle*.
        /// </summary>
        public static string lblCycleRequired {
            get {
                return ResourceManager.GetString("lblCycleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles Total:.
        /// </summary>
        public static string lblCyclesTotal {
            get {
                return ResourceManager.GetString("lblCyclesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Certificate.
        /// </summary>
        public static string lblElectronicCertificate {
            get {
                return ResourceManager.GetString("lblElectronicCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Folio.
        /// </summary>
        public static string lblEnterFolio {
            get {
                return ResourceManager.GetString("lblEnterFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Issuing Date.
        /// </summary>
        public static string lblEnterIssuingDate {
            get {
                return ResourceManager.GetString("lblEnterIssuingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Issuing Date using the format YYYY-MM-DD.
        /// </summary>
        public static string lblEnterValidFormat {
            get {
                return ResourceManager.GetString("lblEnterValidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one course before you can continue the process to generate an electronic certificate.
        /// </summary>
        public static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Date of Birth&quot; is missing.
        /// </summary>
        public static string lblErrorBirthDate {
            get {
                return ResourceManager.GetString("lblErrorBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Campus SEP ID&quot; has not been mapped..
        /// </summary>
        public static string lblErrorCampusSepId {
            get {
                return ResourceManager.GetString("lblErrorCampusSepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;CURP&quot; has not been mapped..
        /// </summary>
        public static string lblErrorCurp {
            get {
                return ResourceManager.GetString("lblErrorCurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set a cycle for each course included and then you can continue the process to generate an electronic certificate.
        /// </summary>
        public static string lblErrorCycle {
            get {
                return ResourceManager.GetString("lblErrorCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Federal Entity&quot; has not been mapped..
        /// </summary>
        public static string lblErrorFederalEntity {
            get {
                return ResourceManager.GetString("lblErrorFederalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Federal Entity catalog mapping&quot; has not been mapped..
        /// </summary>
        public static string lblErrorFederalEntityCatalogMapping {
            get {
                return ResourceManager.GetString("lblErrorFederalEntityCatalogMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;First Surname&quot; has not been mapped..
        /// </summary>
        public static string lblErrorFirstSurname {
            get {
                return ResourceManager.GetString("lblErrorFirstSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The retrieved value doesn&apos;t correspond with the available options.
        /// </summary>
        public static string lblErrorGenderIdentity {
            get {
                return ResourceManager.GetString("lblErrorGenderIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;ID&quot; has not been mapped..
        /// </summary>
        public static string lblErrorId {
            get {
                return ResourceManager.GetString("lblErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Institution SEP ID&quot; has not been mapped..
        /// </summary>
        public static string lblErrorInstitutionSepId {
            get {
                return ResourceManager.GetString("lblErrorInstitutionSepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Issuing date&quot; has not been mapped..
        /// </summary>
        public static string lblErrorIssuingDate {
            get {
                return ResourceManager.GetString("lblErrorIssuingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Job Title&quot; has not been mapped..
        /// </summary>
        public static string lblErrorJobTitle {
            get {
                return ResourceManager.GetString("lblErrorJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request to generate an electronic certificate. Please, review the log files for more details..
        /// </summary>
        public static string lblErrorLegend {
            get {
                return ResourceManager.GetString("lblErrorLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of characters allowed is 40..
        /// </summary>
        public static string lblErrorMaxChar {
            get {
                return ResourceManager.GetString("lblErrorMaxChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Maximum Grade&quot; has not been mapped..
        /// </summary>
        public static string lblErrorMaximumGrade {
            get {
                return ResourceManager.GetString("lblErrorMaximumGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Minimum Grade&quot; has not been mapped..
        /// </summary>
        public static string lblErrorMinimumGrade {
            get {
                return ResourceManager.GetString("lblErrorMinimumGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Minimum Passing Grade&quot; has not been mapped..
        /// </summary>
        public static string lblErrorMinimumPassingGrade {
            get {
                return ResourceManager.GetString("lblErrorMinimumPassingGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Name&quot; has not been mapped..
        /// </summary>
        public static string lblErrorName {
            get {
                return ResourceManager.GetString("lblErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Number&quot; has not been mapped..
        /// </summary>
        public static string lblErrorNumber {
            get {
                return ResourceManager.GetString("lblErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;People ID&quot; has not been mapped..
        /// </summary>
        public static string lblErrorPeopleID {
            get {
                return ResourceManager.GetString("lblErrorPeopleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Period Type&quot; has not been mapped..
        /// </summary>
        public static string lblErrorPeriodType {
            get {
                return ResourceManager.GetString("lblErrorPeriodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Plan Code&quot; has not been mapped..
        /// </summary>
        public static string lblErrorPlanCode {
            get {
                return ResourceManager.GetString("lblErrorPlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;SigningInstitutionId&quot; has not been mapped..
        /// </summary>
        public static string lblErrorSigningInstitutionId {
            get {
                return ResourceManager.GetString("lblErrorSigningInstitutionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Study Level&quot; has not been mapped..
        /// </summary>
        public static string lblErrorStudyLevel {
            get {
                return ResourceManager.GetString("lblErrorStudyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal Entity.
        /// </summary>
        public static string lblFederalEntity {
            get {
                return ResourceManager.GetString("lblFederalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal Entity Catalog Mapping.
        /// </summary>
        public static string lblFederalEntityCatalogMapping {
            get {
                return ResourceManager.GetString("lblFederalEntityCatalogMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal Entity ID:.
        /// </summary>
        public static string lblFederalEntityIdPreview {
            get {
                return ResourceManager.GetString("lblFederalEntityIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal Entity:.
        /// </summary>
        public static string lblFederalEntityPreview {
            get {
                return ResourceManager.GetString("lblFederalEntityPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string lblFemale {
            get {
                return ResourceManager.GetString("lblFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Surname.
        /// </summary>
        public static string lblFirstSurname {
            get {
                return ResourceManager.GetString("lblFirstSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Surname:.
        /// </summary>
        public static string lblFirstSurnamePreview {
            get {
                return ResourceManager.GetString("lblFirstSurnamePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        public static string lblFolio {
            get {
                return ResourceManager.GetString("lblFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio:.
        /// </summary>
        public static string lblFolioPreview {
            get {
                return ResourceManager.GetString("lblFolioPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Identity.
        /// </summary>
        public static string lblGenderIdentity {
            get {
                return ResourceManager.GetString("lblGenderIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Identity:.
        /// </summary>
        public static string lblGenderIdentityPreview {
            get {
                return ResourceManager.GetString("lblGenderIdentityPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string lblGenerate {
            get {
                return ResourceManager.GetString("lblGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Electronic Certificates.
        /// </summary>
        public static string lblGenerateElectronicCertificates {
            get {
                return ResourceManager.GetString("lblGenerateElectronicCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate New.
        /// </summary>
        public static string lblGenerateNew {
            get {
                return ResourceManager.GetString("lblGenerateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string lblGrade {
            get {
                return ResourceManager.GetString("lblGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade*.
        /// </summary>
        public static string lblGradeRequired {
            get {
                return ResourceManager.GetString("lblGradeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string lblIdPreview {
            get {
                return ResourceManager.GetString("lblIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID*.
        /// </summary>
        public static string lblIdRequired {
            get {
                return ResourceManager.GetString("lblIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string lblInclude {
            get {
                return ResourceManager.GetString("lblInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string lblInstitution {
            get {
                return ResourceManager.GetString("lblInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution SEP ID field has not been mapped in the institution-campus setup.
        /// </summary>
        public static string lblInstitutionCodeConflict {
            get {
                return ResourceManager.GetString("lblInstitutionCodeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Name.
        /// </summary>
        public static string lblInstitutionName {
            get {
                return ResourceManager.GetString("lblInstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Name ID.
        /// </summary>
        public static string lblInstitutionSepId {
            get {
                return ResourceManager.GetString("lblInstitutionSepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Certificate.
        /// </summary>
        public static string lblIssuingCertificate {
            get {
                return ResourceManager.GetString("lblIssuingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Total Certificate.
        /// </summary>
        public static string lblIssuingCertificateModalTitle {
            get {
                return ResourceManager.GetString("lblIssuingCertificateModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Date.
        /// </summary>
        public static string lblIssuingDate {
            get {
                return ResourceManager.GetString("lblIssuingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Date:.
        /// </summary>
        public static string lblIssuingDatePreview {
            get {
                return ResourceManager.GetString("lblIssuingDatePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Degree.
        /// </summary>
        public static string lblIssuingDegree {
            get {
                return ResourceManager.GetString("lblIssuingDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Place.
        /// </summary>
        public static string lblIssuingPlace {
            get {
                return ResourceManager.GetString("lblIssuingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Place ID:.
        /// </summary>
        public static string lblIssuingPlaceIdPreview {
            get {
                return ResourceManager.GetString("lblIssuingPlaceIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Place:.
        /// </summary>
        public static string lblIssuingPlacePreview {
            get {
                return ResourceManager.GetString("lblIssuingPlacePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string lblJobTitle {
            get {
                return ResourceManager.GetString("lblJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title ID:.
        /// </summary>
        public static string lblJobTitleIdPreview {
            get {
                return ResourceManager.GetString("lblJobTitleIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title:.
        /// </summary>
        public static string lblJobTitlePreview {
            get {
                return ResourceManager.GetString("lblJobTitlePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assigned courses are less than the total courses..
        /// </summary>
        public static string lblLessTotalCourses {
            get {
                return ResourceManager.GetString("lblLessTotalCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The obtained credits are less than the total credits..
        /// </summary>
        public static string lblLessTotalCredits {
            get {
                return ResourceManager.GetString("lblLessTotalCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string lblMajor {
            get {
                return ResourceManager.GetString("lblMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string lblMale {
            get {
                return ResourceManager.GetString("lblMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Grade.
        /// </summary>
        public static string lblMaximumGrade {
            get {
                return ResourceManager.GetString("lblMaximumGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Grade:.
        /// </summary>
        public static string lblMaximumGradePreview {
            get {
                return ResourceManager.GetString("lblMaximumGradePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Grade.
        /// </summary>
        public static string lblMinimumGrade {
            get {
                return ResourceManager.GetString("lblMinimumGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Grade:.
        /// </summary>
        public static string lblMinimumGradePreview {
            get {
                return ResourceManager.GetString("lblMinimumGradePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Passing grade.
        /// </summary>
        public static string lblMinimumPassingGrade {
            get {
                return ResourceManager.GetString("lblMinimumPassingGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Passing Grade:.
        /// </summary>
        public static string lblMinPassingGradePreview {
            get {
                return ResourceManager.GetString("lblMinPassingGradePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name ID:.
        /// </summary>
        public static string lblNameIdPreview {
            get {
                return ResourceManager.GetString("lblNameIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string lblNamePreview {
            get {
                return ResourceManager.GetString("lblNamePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your operator account has no campus assigned.
        /// </summary>
        public static string lblNoCampusAssigned {
            get {
                return ResourceManager.GetString("lblNoCampusAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No studies programs to show..
        /// </summary>
        public static string lblNoStudiesPrograms {
            get {
                return ResourceManager.GetString("lblNoStudiesPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string lblNumber {
            get {
                return ResourceManager.GetString("lblNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string lblNumberPreview {
            get {
                return ResourceManager.GetString("lblNumberPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string lblObservations {
            get {
                return ResourceManager.GetString("lblObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained Credits.
        /// </summary>
        public static string lblObtainedCredits {
            get {
                return ResourceManager.GetString("lblObtainedCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained Credits:.
        /// </summary>
        public static string lblObtainedCreditsPreview {
            get {
                return ResourceManager.GetString("lblObtainedCreditsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This campus is not assigned to your operator account..
        /// </summary>
        public static string lblOperatorCampusConflict {
            get {
                return ResourceManager.GetString("lblOperatorCampusConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People ID.
        /// </summary>
        public static string lblPeopleID {
            get {
                return ResourceManager.GetString("lblPeopleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People ID:.
        /// </summary>
        public static string lblPeopleIdPreview {
            get {
                return ResourceManager.GetString("lblPeopleIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Type.
        /// </summary>
        public static string lblPeriodType {
            get {
                return ResourceManager.GetString("lblPeriodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Type ID:.
        /// </summary>
        public static string lblPeriodTypeIdPreview {
            get {
                return ResourceManager.GetString("lblPeriodTypeIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Type:.
        /// </summary>
        public static string lblPeriodTypePreview {
            get {
                return ResourceManager.GetString("lblPeriodTypePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Code.
        /// </summary>
        public static string lblPlanCode {
            get {
                return ResourceManager.GetString("lblPlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Code:.
        /// </summary>
        public static string lblPlanCodePreview {
            get {
                return ResourceManager.GetString("lblPlanCodePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Data.
        /// </summary>
        public static string lblPreviewData {
            get {
                return ResourceManager.GetString("lblPreviewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview &amp; Generate.
        /// </summary>
        public static string lblPreviewGenerate {
            get {
                return ResourceManager.GetString("lblPreviewGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string lblProgram {
            get {
                return ResourceManager.GetString("lblProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string lblResponsible {
            get {
                return ResourceManager.GetString("lblResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This campus does not have a responsible assigned..
        /// </summary>
        public static string lblResponsibleCampusConflict {
            get {
                return ResourceManager.GetString("lblResponsibleCampusConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVOE.
        /// </summary>
        public static string lblRvoe {
            get {
                return ResourceManager.GetString("lblRvoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RVOE information is not complete..
        /// </summary>
        public static string lblRvoeInfoConflict {
            get {
                return ResourceManager.GetString("lblRvoeInfoConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Surname.
        /// </summary>
        public static string lblSecondSurname {
            get {
                return ResourceManager.GetString("lblSecondSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Surname:.
        /// </summary>
        public static string lblSecondSurnamePreview {
            get {
                return ResourceManager.GetString("lblSecondSurnamePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section:.
        /// </summary>
        public static string lblSection {
            get {
                return ResourceManager.GetString("lblSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Certification Type.
        /// </summary>
        public static string lblSelectCertificationType {
            get {
                return ResourceManager.GetString("lblSelectCertificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Issuing Place.
        /// </summary>
        public static string lblSelectIssuingPlace {
            get {
                return ResourceManager.GetString("lblSelectIssuingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Institution ID field has not been mapped in the institution-campus setup.
        /// </summary>
        public static string lblSigningCodeConflict {
            get {
                return ResourceManager.GetString("lblSigningCodeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Institution ID:.
        /// </summary>
        public static string lblSigningInstitutionId {
            get {
                return ResourceManager.GetString("lblSigningInstitutionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string lblStudent {
            get {
                return ResourceManager.GetString("lblStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studies Programs.
        /// </summary>
        public static string lblStudiesPrograms {
            get {
                return ResourceManager.GetString("lblStudiesPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the option for which the degree needs to be generated:.
        /// </summary>
        public static string lblStudiesProgramsInstructions {
            get {
                return ResourceManager.GetString("lblStudiesProgramsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studies Programs Status.
        /// </summary>
        public static string lblStudiesProgramsStatus {
            get {
                return ResourceManager.GetString("lblStudiesProgramsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Level.
        /// </summary>
        public static string lblStudyLevel {
            get {
                return ResourceManager.GetString("lblStudyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Level ID:.
        /// </summary>
        public static string lblStudyLevelIdPreview {
            get {
                return ResourceManager.GetString("lblStudyLevelIdPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Level:.
        /// </summary>
        public static string lblStudyLevelPreview {
            get {
                return ResourceManager.GetString("lblStudyLevelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string lblTerm {
            get {
                return ResourceManager.GetString("lblTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Courses.
        /// </summary>
        public static string lblTotalCourses {
            get {
                return ResourceManager.GetString("lblTotalCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credits.
        /// </summary>
        public static string lblTotalCredits {
            get {
                return ResourceManager.GetString("lblTotalCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credits:.
        /// </summary>
        public static string lblTotalCreditsPreview {
            get {
                return ResourceManager.GetString("lblTotalCreditsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string lblTotalPreview {
            get {
                return ResourceManager.GetString("lblTotalPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string lblType1 {
            get {
                return ResourceManager.GetString("lblType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type*.
        /// </summary>
        public static string lblTypeRequired {
            get {
                return ResourceManager.GetString("lblTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string lblValidate {
            get {
                return ResourceManager.GetString("lblValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Data.
        /// </summary>
        public static string lblViewData {
            get {
                return ResourceManager.GetString("lblViewData", resourceCulture);
            }
        }
    }
}
