//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicCertificate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Institution {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Institution() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicCertificate.Institution", typeof(Institution).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Record.
        /// </summary>
        public static string lblAcademicRecord {
            get {
                return ResourceManager.GetString("lblAcademicRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string lblApply {
            get {
                return ResourceManager.GetString("lblApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        public static string lblCampus {
            get {
                return ResourceManager.GetString("lblCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus SEP Code.
        /// </summary>
        public static string lblCampusSepCode {
            get {
                return ResourceManager.GetString("lblCampusSepCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Certificate.
        /// </summary>
        public static string lblElectronicCertificate {
            get {
                return ResourceManager.GetString("lblElectronicCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Place.
        /// </summary>
        public static string lblFederalEntity {
            get {
                return ResourceManager.GetString("lblFederalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        public static string lblFolio {
            get {
                return ResourceManager.GetString("lblFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Control Folio.
        /// </summary>
        public static string lblFolioFormat {
            get {
                return ResourceManager.GetString("lblFolioFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Certificate Control Folio.
        /// </summary>
        public static string lblFolioFormatRequired {
            get {
                return ResourceManager.GetString("lblFolioFormatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio Tokens.
        /// </summary>
        public static string lblFolioTokens {
            get {
                return ResourceManager.GetString("lblFolioTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built the default setting for the generation of certificate control folios, this field will be open for free modification in the generation of each certificate..
        /// </summary>
        public static string lblFolioWarning {
            get {
                return ResourceManager.GetString("lblFolioWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Name ID.
        /// </summary>
        public static string lblInsitutionSepId {
            get {
                return ResourceManager.GetString("lblInsitutionSepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string lblInstitution {
            get {
                return ResourceManager.GetString("lblInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution-Campus.
        /// </summary>
        public static string lblInstitutionCampus {
            get {
                return ResourceManager.GetString("lblInstitutionCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions-Campuses.
        /// </summary>
        public static string lblInstitutionCampuses {
            get {
                return ResourceManager.GetString("lblInstitutionCampuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.Code.
        /// </summary>
        public static string lblInstitutionCode {
            get {
                return ResourceManager.GetString("lblInstitutionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.Name.
        /// </summary>
        public static string lblInstitutionName {
            get {
                return ResourceManager.GetString("lblInstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Institution-Campuses to show..
        /// </summary>
        public static string lblNoInstitutionCampuses {
            get {
                return ResourceManager.GetString("lblNoInstitutionCampuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string lblResponsible {
            get {
                return ResourceManager.GetString("lblResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string lblSetup {
            get {
                return ResourceManager.GetString("lblSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Institution ID.
        /// </summary>
        public static string lblSigningInstitutionId {
            get {
                return ResourceManager.GetString("lblSigningInstitutionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.Curp.
        /// </summary>
        public static string lblStudentCurp {
            get {
                return ResourceManager.GetString("lblStudentCurp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.FirstName.
        /// </summary>
        public static string lblStudentFirstName {
            get {
                return ResourceManager.GetString("lblStudentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.FirstSurname.
        /// </summary>
        public static string lblStudentFirstSurname {
            get {
                return ResourceManager.GetString("lblStudentFirstSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.PeopleId.
        /// </summary>
        public static string lblStudentPeopleId {
            get {
                return ResourceManager.GetString("lblStudentPeopleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.SecondSurname.
        /// </summary>
        public static string lblStudentSecondSurname {
            get {
                return ResourceManager.GetString("lblStudentSecondSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens selected in Certificate Control Folio can creates Folios that exceds 40 characters and that is not allowed by SEP..
        /// </summary>
        public static string lblTokensWarning {
            get {
                return ResourceManager.GetString("lblTokensWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter at least 5 numeric characters.
        /// </summary>
        public static string lblValidateCharacters {
            get {
                return ResourceManager.GetString("lblValidateCharacters", resourceCulture);
            }
        }
    }
}
