//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicCertificate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Operator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Operator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicCertificate.Operator", typeof(Operator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Operator.
        /// </summary>
        public static string lblAddOperator {
            get {
                return ResourceManager.GetString("lblAddOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Visualization Permissions.
        /// </summary>
        public static string lblAddVisualizationPer {
            get {
                return ResourceManager.GetString("lblAddVisualizationPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string lblApply {
            get {
                return ResourceManager.GetString("lblApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        public static string lblCampus {
            get {
                return ResourceManager.GetString("lblCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campuses.
        /// </summary>
        public static string lblCampuses {
            get {
                return ResourceManager.GetString("lblCampuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this operator?   Deleting this operator will remove it form your list..
        /// </summary>
        public static string lblDeleteLegend {
            get {
                return ResourceManager.GetString("lblDeleteLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Operator.
        /// </summary>
        public static string lblEditOperator {
            get {
                return ResourceManager.GetString("lblEditOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;There are duplicate campuses. You must remove duplicate campuses before saving&quot;.
        /// </summary>
        public static string lblErrorDuplicate {
            get {
                return ResourceManager.GetString("lblErrorDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Place.
        /// </summary>
        public static string lblIssuingPlace {
            get {
                return ResourceManager.GetString("lblIssuingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Campus to show, click the Add button to assign a Campus to this Operator..
        /// </summary>
        public static string lblNoInstitutions {
            get {
                return ResourceManager.GetString("lblNoInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operators to show, click the Add button to start..
        /// </summary>
        public static string lblNoOperators {
            get {
                return ResourceManager.GetString("lblNoOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Visualization Permissions to show, click the add button to assign Visualization Permissions to this Operator..
        /// </summary>
        public static string lblNoVisualizationPer {
            get {
                return ResourceManager.GetString("lblNoVisualizationPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Campuses.
        /// </summary>
        public static string lblNumberCampus {
            get {
                return ResourceManager.GetString("lblNumberCampus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        public static string lblNumberId {
            get {
                return ResourceManager.GetString("lblNumberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Visualization Permissions.
        /// </summary>
        public static string lblNumberVisualizationPer {
            get {
                return ResourceManager.GetString("lblNumberVisualizationPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string lblOperator {
            get {
                return ResourceManager.GetString("lblOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator ID.
        /// </summary>
        public static string lblOperatorId {
            get {
                return ResourceManager.GetString("lblOperatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string lblOperators {
            get {
                return ResourceManager.GetString("lblOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string lblRemove {
            get {
                return ResourceManager.GetString("lblRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Visualization Permission.
        /// </summary>
        public static string lblRemoveVisualizationPer {
            get {
                return ResourceManager.GetString("lblRemoveVisualizationPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string lblSavedSuccesfull {
            get {
                return ResourceManager.GetString("lblSavedSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Operators to add Visualization Permissions..
        /// </summary>
        public static string lblSearchLegend {
            get {
                return ResourceManager.GetString("lblSearchLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization Permissions.
        /// </summary>
        public static string lblVisualizationPer {
            get {
                return ResourceManager.GetString("lblVisualizationPer", resourceCulture);
            }
        }
    }
}
