//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicCertificate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PdcCourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdcCourse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicCertificate.PdcCourse", typeof(PdcCourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string lblClassification {
            get {
                return ResourceManager.GetString("lblClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string lblCourses {
            get {
                return ResourceManager.GetString("lblCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string lblCredits {
            get {
                return ResourceManager.GetString("lblCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        public static string lblDiscipline {
            get {
                return ResourceManager.GetString("lblDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog ID.
        /// </summary>
        public static string lblEventId {
            get {
                return ResourceManager.GetString("lblEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblEventName {
            get {
                return ResourceManager.GetString("lblEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype.
        /// </summary>
        public static string lblEventSubType {
            get {
                return ResourceManager.GetString("lblEventSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Progress : {0}%.
        /// </summary>
        public static string lblMappingProgress {
            get {
                return ResourceManager.GetString("lblMappingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is missing.
        /// </summary>
        public static string lblMissing {
            get {
                return ResourceManager.GetString("lblMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP ID*.
        /// </summary>
        public static string lblSepId {
            get {
                return ResourceManager.GetString("lblSepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblSubjectTypeId {
            get {
                return ResourceManager.GetString("lblSubjectTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Layout.
        /// </summary>
        public static string lblUploadLayout {
            get {
                return ResourceManager.GetString("lblUploadLayout", resourceCulture);
            }
        }
    }
}
