//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Resources.ElectronicCertificate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Setup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Resources.ElectronicCertificate.Setup", typeof(Setup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Plan.
        /// </summary>
        public static string lblAcademicPlan {
            get {
                return ResourceManager.GetString("lblAcademicPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs.
        /// </summary>
        public static string lblCatalogs {
            get {
                return ResourceManager.GetString("lblCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions-Campuses.
        /// </summary>
        public static string lblInstitutionsCampuses {
            get {
                return ResourceManager.GetString("lblInstitutionsCampuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string lblOperators {
            get {
                return ResourceManager.GetString("lblOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibles.
        /// </summary>
        public static string lblResponsibles {
            get {
                return ResourceManager.GetString("lblResponsibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Electronic Certificate.
        /// </summary>
        public static string lblSetupElectronicCertificate {
            get {
                return ResourceManager.GetString("lblSetupElectronicCertificate", resourceCulture);
            }
        }
    }
}
