//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Models.Resources.AboutViewModelResource", typeof(AboutViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build date:.
        /// </summary>
        public static string lblBuildDate {
            get {
                return ResourceManager.GetString("lblBuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        public static string lblCopyright {
            get {
                return ResourceManager.GetString("lblCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} Ellucian Company L.P. and its affiliates..
        /// </summary>
        public static string lblCopyright1 {
            get {
                return ResourceManager.GetString("lblCopyright1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software contains confidential and proprietary information of Ellucian or its subsidiaries.
        ///Use of this software is limited to Ellucian licensees, and is subject to the terms and
        ///conditions of one or more written license agreements between Ellucian and such licensees..
        /// </summary>
        public static string lblCopyright2 {
            get {
                return ResourceManager.GetString("lblCopyright2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerCampus Web Administration Services Version:.
        /// </summary>
        public static string lblFiscalRecordsServicesVersion {
            get {
                return ResourceManager.GetString("lblFiscalRecordsServicesVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerCampus Web Administration Version:.
        /// </summary>
        public static string lblFiscalRecordsUIVersion {
            get {
                return ResourceManager.GetString("lblFiscalRecordsUIVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About PowerCampus Web Administration .
        /// </summary>
        public static string lblPageTitle {
            get {
                return ResourceManager.GetString("lblPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trademark:.
        /// </summary>
        public static string lblTrademark {
            get {
                return ResourceManager.GetString("lblTrademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner®, Colleague®, Ellucian®, and Luminis® are trademarks of Ellucian Company L.P. or its affiliates and are registered in the U.S. and other countries. Ellucian Advance™, Ellucian Course Signals™, Ellucian Degree Works™, Ellucian PowerCampus™, Ellucian Recruiter™, Ellucian SmartCall™, and are trademarks of Ellucian Company L.P. or its affiliates. Other names may be trademarks of their respective owners..
        /// </summary>
        public static string lblTrademark1 {
            get {
                return ResourceManager.GetString("lblTrademark1", resourceCulture);
            }
        }
    }
}
