//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChargeCreditMappingModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChargeCreditMappingModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Models.Resources.ChargeCreditMappingModelResource", typeof(ChargeCreditMappingModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mapping.
        /// </summary>
        public static string AddMapping {
            get {
                return ResourceManager.GetString("AddMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Tax Profile.
        /// </summary>
        public static string AssignTaxProfile {
            get {
                return ResourceManager.GetString("AssignTaxProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the tax profile to assign for all charges selected without a tax profile.
        /// </summary>
        public static string AssignTaxProfileInstructions {
            get {
                return ResourceManager.GetString("AssignTaxProfileInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Code.
        /// </summary>
        public static string ChargeCreditCode {
            get {
                return ResourceManager.GetString("ChargeCreditCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least a charge credit code.
        /// </summary>
        public static string ChargeCreditCodeRequired {
            get {
                return ResourceManager.GetString("ChargeCreditCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a charge code.
        /// </summary>
        public static string ChargeCreditRequired {
            get {
                return ResourceManager.GetString("ChargeCreditRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total results: {0}.
        /// </summary>
        public static string FormatTotal {
            get {
                return ResourceManager.GetString("FormatTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mapping.
        /// </summary>
        public static string MappingMissing {
            get {
                return ResourceManager.GetString("MappingMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product/Service Code.
        /// </summary>
        public static string ProductService {
            get {
                return ResourceManager.GetString("ProductService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a product/service code.
        /// </summary>
        public static string ProductServiceRequired {
            get {
                return ResourceManager.GetString("ProductServiceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Profile.
        /// </summary>
        public static string TaxProfile {
            get {
                return ResourceManager.GetString("TaxProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Code.
        /// </summary>
        public static string Unity {
            get {
                return ResourceManager.GetString("Unity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a unit code.
        /// </summary>
        public static string UnityRequired {
            get {
                return ResourceManager.GetString("UnityRequired", resourceCulture);
            }
        }
    }
}
