//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FiscalRecordModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FiscalRecordModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Models.Resources.FiscalRecordModelResource", typeof(FiscalRecordModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedition date.
        /// </summary>
        public static string lblExpeditionDate {
            get {
                return ResourceManager.GetString("lblExpeditionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        public static string lblFolio {
            get {
                return ResourceManager.GetString("lblFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship type.
        /// </summary>
        public static string lblRelationshipType {
            get {
                return ResourceManager.GetString("lblRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string lblSerial {
            get {
                return ResourceManager.GetString("lblSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID.
        /// </summary>
        public static string lblUUID {
            get {
                return ResourceManager.GetString("lblUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Cannot Cancel.
        /// </summary>
        public static string ProviderCannotCancel {
            get {
                return ResourceManager.GetString("ProviderCannotCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Cannot Create.
        /// </summary>
        public static string ProviderCannotCreate {
            get {
                return ResourceManager.GetString("ProviderCannotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Is Canceling.
        /// </summary>
        public static string ProviderIsCanceling {
            get {
                return ResourceManager.GetString("ProviderIsCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Is Creating.
        /// </summary>
        public static string ProviderIsCreating {
            get {
                return ResourceManager.GetString("ProviderIsCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Cancelation.
        /// </summary>
        public static string RequestedCancellation {
            get {
                return ResourceManager.GetString("RequestedCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Fiscal Record.
        /// </summary>
        public static string RequestedFiscalRecord {
            get {
                return ResourceManager.GetString("RequestedFiscalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07 - CFDI for advance payment.
        /// </summary>
        public static string txtRelationshipTypeAdvancePayment {
            get {
                return ResourceManager.GetString("txtRelationshipTypeAdvancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 - Credit note of related documents.
        /// </summary>
        public static string txtRelationshipTypeCreditNote {
            get {
                return ResourceManager.GetString("txtRelationshipTypeCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02 - Debit note of related documents.
        /// </summary>
        public static string txtRelationshipTypeDebitNote {
            get {
                return ResourceManager.GetString("txtRelationshipTypeDebitNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06 - Invoice generated by previous transfers.
        /// </summary>
        public static string txtRelationshipTypeInvoiceByTransfers {
            get {
                return ResourceManager.GetString("txtRelationshipTypeInvoiceByTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04 - Replacement of previous CFDIs.
        /// </summary>
        public static string txtRelationshipTypeReplacementCFDI {
            get {
                return ResourceManager.GetString("txtRelationshipTypeReplacementCFDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03 - Return of merchandise on invoices or previous transfers.
        /// </summary>
        public static string txtRelationshipTypeReturnMerchandise {
            get {
                return ResourceManager.GetString("txtRelationshipTypeReturnMerchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05 - Goods transfers previously invoiced.
        /// </summary>
        public static string txtRelationshipTypeTransfersInvoiced {
            get {
                return ResourceManager.GetString("txtRelationshipTypeTransfersInvoiced", resourceCulture);
            }
        }
    }
}
