//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssuerModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssuerModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Models.Resources.IssuerModelResource", typeof(IssuerModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Name.
        /// </summary>
        public static string CorporateName {
            get {
                return ResourceManager.GetString("CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Name is Required.
        /// </summary>
        public static string CorporateNameRequired {
            get {
                return ResourceManager.GetString("CorporateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name or corporate name.
        /// </summary>
        public static string CorporateNameValidation {
            get {
                return ResourceManager.GetString("CorporateNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is Required.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description.
        /// </summary>
        public static string DescriptionValidation {
            get {
                return ResourceManager.GetString("DescriptionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedition Address.
        /// </summary>
        public static string ExpeditionAddress {
            get {
                return ResourceManager.GetString("ExpeditionAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedition Description.
        /// </summary>
        public static string ExpeditionDescription {
            get {
                return ResourceManager.GetString("ExpeditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Folio.
        /// </summary>
        public static string InitialFolio {
            get {
                return ResourceManager.GetString("InitialFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Folio is Required.
        /// </summary>
        public static string InitialFolioRequired {
            get {
                return ResourceManager.GetString("InitialFolioRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a initial folio.
        /// </summary>
        public static string InitialFolioValidation {
            get {
                return ResourceManager.GetString("InitialFolioValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name or corporate name.
        /// </summary>
        public static string InvalidCorporateName {
            get {
                return ResourceManager.GetString("InvalidCorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio is from 1 to 2147483647.
        /// </summary>
        public static string InvalidFolio {
            get {
                return ResourceManager.GetString("InvalidFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxpayer is invalid.
        /// </summary>
        public static string InvalidTaxpayer {
            get {
                return ResourceManager.GetString("InvalidTaxpayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Folio.
        /// </summary>
        public static string LastFolio {
            get {
                return ResourceManager.GetString("LastFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 12 or 13 charecters alowed, TaxPayer is invalid.
        /// </summary>
        public static string MaxlengthTaxpayer {
            get {
                return ResourceManager.GetString("MaxlengthTaxpayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial is Required.
        /// </summary>
        public static string SerialNumberRequired {
            get {
                return ResourceManager.GetString("SerialNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a serial number.
        /// </summary>
        public static string SerialNumberValidation {
            get {
                return ResourceManager.GetString("SerialNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxpayer id.
        /// </summary>
        public static string TaxpayerId {
            get {
                return ResourceManager.GetString("TaxpayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxPayer is Required.
        /// </summary>
        public static string TaxpayerIdRequired {
            get {
                return ResourceManager.GetString("TaxpayerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a taxpayerid.
        /// </summary>
        public static string TaxPayerIdValidation {
            get {
                return ResourceManager.GetString("TaxPayerIdValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Regimen.
        /// </summary>
        public static string TaxRegimen {
            get {
                return ResourceManager.GetString("TaxRegimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxRegimen is Required.
        /// </summary>
        public static string TaxRegimenRequired {
            get {
                return ResourceManager.GetString("TaxRegimenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tax regimen.
        /// </summary>
        public static string TaxRegimenValidation {
            get {
                return ResourceManager.GetString("TaxRegimenValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code is invalid.
        /// </summary>
        public static string ZipCodeInvalid {
            get {
                return ResourceManager.GetString("ZipCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Zip Code is not in the SAT catalog..
        /// </summary>
        public static string ZipCodeNotInCatalog {
            get {
                return ResourceManager.GetString("ZipCodeNotInCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code is Required.
        /// </summary>
        public static string ZipCodeRequired {
            get {
                return ResourceManager.GetString("ZipCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a zip code.
        /// </summary>
        public static string ZipCodeValidation {
            get {
                return ResourceManager.GetString("ZipCodeValidation", resourceCulture);
            }
        }
    }
}
