//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdminUI.Views.Issuers.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssuerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssuerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAdminUI.Views.Issuers.App_LocalResources.IssuerResource", typeof(IssuerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Address.
        /// </summary>
        public static string AddIssuerAddress {
            get {
                return ResourceManager.GetString("AddIssuerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Document.
        /// </summary>
        public static string AddIssuerDocument {
            get {
                return ResourceManager.GetString("AddIssuerDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Issuer Document by Address.
        /// </summary>
        public static string AddIssuerDocumentByAddress {
            get {
                return ResourceManager.GetString("AddIssuerDocumentByAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Issuer Document by Taxpayer Id.
        /// </summary>
        public static string AddIssuerDocumentByTaxpayer {
            get {
                return ResourceManager.GetString("AddIssuerDocumentByTaxpayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Issuer Address.
        /// </summary>
        public static string AddNewIssuerAddress {
            get {
                return ResourceManager.GetString("AddNewIssuerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Issuer Document.
        /// </summary>
        public static string AddNewIssuerDocument {
            get {
                return ResourceManager.GetString("AddNewIssuerDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new mapping.
        /// </summary>
        public static string AddNewMapping {
            get {
                return ResourceManager.GetString("AddNewMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Issuer.
        /// </summary>
        public static string BackIssuer {
            get {
                return ResourceManager.GetString("BackIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAddIssuer {
            get {
                return ResourceManager.GetString("btnAddIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit code to amount refund.
        /// </summary>
        public static string ChargeCreditCode {
            get {
                return ResourceManager.GetString("ChargeCreditCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit code to tax refund.
        /// </summary>
        public static string ChargeCreditCodeTax {
            get {
                return ResourceManager.GetString("ChargeCreditCodeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corporate name must be recorded as it appears on the &quot;Cédula de Identificación Fiscal&quot; and &quot;Constancia de Situación Fiscal.
        /// </summary>
        public static string CorporateNameMessage {
            get {
                return ResourceManager.GetString("CorporateNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Notes.
        /// </summary>
        public static string CreditNotes {
            get {
                return ResourceManager.GetString("CreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Issuer Address.
        /// </summary>
        public static string DeleteIssuerAddress {
            get {
                return ResourceManager.GetString("DeleteIssuerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Issuer.
        /// </summary>
        public static string EditIssuer {
            get {
                return ResourceManager.GetString("EditIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Issuer Address.
        /// </summary>
        public static string EditIssuerAddress {
            get {
                return ResourceManager.GetString("EditIssuerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Record.
        /// </summary>
        public static string EditRecord {
            get {
                return ResourceManager.GetString("EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the request.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Initial Folio cannot be lower than the Last Folio generated..
        /// </summary>
        public static string ErrorMessageFolio {
            get {
                return ResourceManager.GetString("ErrorMessageFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folio number is incorrect, please enter a smaller number.
        /// </summary>
        public static string ErrorMessageFolioBig {
            get {
                return ResourceManager.GetString("ErrorMessageFolioBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same Serial and Initial Folio cannot be entered more than once..
        /// </summary>
        public static string ErrorMessageSerial {
            get {
                return ResourceManager.GetString("ErrorMessageSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Data.
        /// </summary>
        public static string GeneralData {
            get {
                return ResourceManager.GetString("GeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Folio.
        /// </summary>
        public static string InitialFolio {
            get {
                return ResourceManager.GetString("InitialFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedition Address.
        /// </summary>
        public static string IssuerAddress {
            get {
                return ResourceManager.GetString("IssuerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Fiscal Information.
        /// </summary>
        public static string IssuerFiscalInformation {
            get {
                return ResourceManager.GetString("IssuerFiscalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer Taxpayer ID.
        /// </summary>
        public static string IssuerTaxPayerID {
            get {
                return ResourceManager.GetString("IssuerTaxPayerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an issuer taxpayer ID.
        /// </summary>
        public static string IssuerTaxPayerIDRequired {
            get {
                return ResourceManager.GetString("IssuerTaxPayerIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Address.
        /// </summary>
        public static string IssuingAddress {
            get {
                return ResourceManager.GetString("IssuingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an issuing address.
        /// </summary>
        public static string IssuingAddressRequired {
            get {
                return ResourceManager.GetString("IssuingAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Folio.
        /// </summary>
        public static string LastFolio {
            get {
                return ResourceManager.GetString("LastFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record.
        /// </summary>
        public static string NewRecord {
            get {
                return ResourceManager.GetString("NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a payment conditions.
        /// </summary>
        public static string PaymentConditionsRequired {
            get {
                return ResourceManager.GetString("PaymentConditionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Conditions.
        /// </summary>
        public static string PaymentContditions {
            get {
                return ResourceManager.GetString("PaymentContditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial for credit notes.
        /// </summary>
        public static string SerialCreditNote {
            get {
                return ResourceManager.GetString("SerialCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial for invoices.
        /// </summary>
        public static string SerialInovice {
            get {
                return ResourceManager.GetString("SerialInovice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a serial.
        /// </summary>
        public static string SerialNumberRequired {
            get {
                return ResourceManager.GetString("SerialNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a serial.
        /// </summary>
        public static string SerialRequired {
            get {
                return ResourceManager.GetString("SerialRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Records Setup.
        /// </summary>
        public static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save was successful.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxpayer exists..
        /// </summary>
        public static string TaxpayerExists {
            get {
                return ResourceManager.GetString("TaxpayerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View List.
        /// </summary>
        public static string ViewList {
            get {
                return ResourceManager.GetString("ViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
